-- Auto-generated by qedgen asm2lean from asm-slippage.s
-- DO NOT EDIT — regenerate with: qedgen asm2lean --input asm-slippage.s

import QEDGen.Solana.SBPF

namespace SlippageProg

open QEDGen.Solana.SBPF

/-! ## .equ constants -/

abbrev TOKEN_ACCOUNT_BALANCE : Int := 0xa0
abbrev MINIMUM_BALANCE : Int := 0x2918

/-! ## Program -/

@[simp] def prog : Program := #[
  .ldx .dword .r3 .r1 MINIMUM_BALANCE,             -- 0: entrypoint
  .ldx .dword .r4 .r1 TOKEN_ACCOUNT_BALANCE,       -- 1
  .jge .r3 (.reg .r4) 4,                           -- 2
  .exit,                                           -- 3
  .lddw .r1 0 /- undefined: e -/,                  -- 4: end
  .lddw .r2 17,                                    -- 5
  .call .sol_log_,                                 -- 6
  .lddw .r0 1,                                     -- 7
  .exit                                             -- 8
]

end SlippageProg
