-- Auto-generated by qedgen asm2lean from tree.s
-- DO NOT EDIT — regenerate with: qedgen asm2lean --input tree.s

import QEDGen.Solana.SBPF

namespace TreeProg

open QEDGen.Solana.SBPF

/-! ## .equ constants -/

abbrev E_N_ACCOUNTS : Nat := 1
abbrev E_USER_DATA_LEN : Nat := 2
abbrev E_TREE_DATA_LEN : Nat := 3
abbrev E_SYSTEM_PROGRAM_DATA_LEN : Nat := 4
abbrev E_TREE_DUPLICATE : Nat := 5
abbrev E_SYSTEM_PROGRAM_DUPLICATE : Nat := 6
abbrev E_RENT_DUPLICATE : Nat := 7
abbrev E_RENT_ADDRESS : Nat := 8
abbrev E_INSTRUCTION_DATA : Nat := 9
abbrev E_PDA_MISMATCH : Nat := 10
abbrev E_INSTRUCTION_DISCRIMINATOR : Nat := 11
abbrev E_INSTRUCTION_DATA_LEN : Nat := 12
abbrev E_N_ACCOUNTS_INSERT_ALLOCATION : Nat := 13
abbrev E_KEY_EXISTS : Nat := 14
abbrev E_KEY_DOES_NOT_EXIST : Nat := 15
abbrev SIZE_OF_U8 : Nat := 1
abbrev SIZE_OF_U64 : Int := 8
abbrev SIZE_OF_ADDRESS : Nat := 32
abbrev SIZE_OF_U128 : Nat := 16
abbrev SIZE_OF_TREE_HEADER : Nat := 24
abbrev SIZE_OF_INITIALIZE_INSTRUCTION : Nat := 1
abbrev SIZE_OF_INSERT_INSTRUCTION : Nat := 5
abbrev SIZE_OF_REMOVE_INSTRUCTION : Nat := 3
abbrev SIZE_OF_TREE_NODE : Nat := 29
abbrev DATA_LEN_ZERO : Nat := 0
abbrev BPF_ALIGN_OF_U128 : Nat := 8
abbrev OFFSET_ZERO : Int := 0
abbrev NULL : Nat := 0
abbrev DATA_LEN_AND_MASK : Int := -8
abbrev MAX_DATA_PAD : Nat := 7
abbrev BOOL_TRUE : Nat := 1
abbrev PUBKEY_CHUNK_OFF_0 : Int := 0
abbrev PUBKEY_CHUNK_OFF_1 : Int := 8
abbrev PUBKEY_CHUNK_OFF_2 : Int := 16
abbrev PUBKEY_CHUNK_OFF_3 : Int := 24
abbrev IB_N_ACCOUNTS_OFF : Int := 0
abbrev IB_USER_ACCOUNT_OFF : Nat := 8
abbrev IB_USER_LAMPORTS_OFF : Nat := 80
abbrev IB_USER_DATA_OFF : Nat := 96
abbrev IB_USER_OWNER_OFF : Nat := 48
abbrev IB_TREE_LAMPORTS_OFF : Nat := 10416
abbrev IB_TREE_DATA_OFF : Nat := 10432
abbrev IB_TREE_OWNER_OFF : Nat := 10384
abbrev IB_TREE_ACCOUNT_OFF : Nat := 10344
abbrev IB_TREE_ADDRESS_OFF : Nat := 10352
abbrev IB_SYSTEM_PROGRAM_ACCOUNT_OFF : Nat := 20680
abbrev IB_RENT_ACCOUNT_OFF : Nat := 31032
abbrev IB_RENT_DATA_OFF : Int := 31120
abbrev IB_N_ACCOUNTS_GENERAL : Nat := 2
abbrev IB_N_ACCOUNTS_INIT : Nat := 4
abbrev IB_SYSTEM_PROGRAM_DATA_LEN : Nat := 14
abbrev IB_RENT_DATA_LEN : Nat := 17
abbrev IB_USER_ADDRESS_OFF : Nat := 16
abbrev IB_USER_DATA_LEN_OFF : Int := 88
abbrev IB_NON_DUP_MARKER : Nat := 255
abbrev IB_TREE_NON_DUP_MARKER_OFF : Int := 10344
abbrev IB_TREE_ADDRESS_OFF_0 : Int := 10352
abbrev IB_TREE_ADDRESS_OFF_1 : Int := 10360
abbrev IB_TREE_ADDRESS_OFF_2 : Int := 10368
abbrev IB_TREE_ADDRESS_OFF_3 : Int := 10376
abbrev IB_TREE_DATA_LEN_OFF : Int := 10424
abbrev IB_SYSTEM_PROGRAM_NON_DUP_MARKER_OFF : Int := 20680
abbrev IB_SYSTEM_PROGRAM_DATA_LEN_OFF : Int := 20760
abbrev IB_RENT_NON_DUP_MARKER_OFF : Int := 31032
abbrev IB_RENT_ADDRESS_OFF_0 : Int := 31040
abbrev IB_RENT_ADDRESS_OFF_1 : Int := 31048
abbrev IB_RENT_ADDRESS_OFF_2 : Int := 31056
abbrev IB_RENT_ADDRESS_OFF_3 : Int := 31064
abbrev IB_RENT_ID_CHUNK_0 : Nat := 5862609301215225606
abbrev IB_RENT_ID_CHUNK_0_LO : Nat := 399877894
abbrev IB_RENT_ID_CHUNK_0_HI : Nat := 1364995097
abbrev IB_RENT_ID_CHUNK_1 : Nat := 9219231539345853473
abbrev IB_RENT_ID_CHUNK_1_LO : Nat := 1288277025
abbrev IB_RENT_ID_CHUNK_1_HI : Nat := 2146519613
abbrev IB_RENT_ID_CHUNK_2 : Nat := 4971307250928769624
abbrev IB_RENT_ID_CHUNK_2_LO : Nat := 149871192
abbrev IB_RENT_ID_CHUNK_2_HI : Nat := 1157472667
abbrev IB_RENT_ID_CHUNK_3 : Nat := 2329533411
abbrev IB_RENT_ID_CHUNK_3_LO : Int := -1965433885
abbrev IB_RENT_ID_CHUNK_3_HI : Nat := 0
abbrev IB_INIT_PROGRAM_ID_OFF_IMM : Nat := 41401
abbrev IB_TREE_DATA_TOP_OFF : Int := 10440
abbrev IB_TREE_DATA_NEXT_OFF : Int := 10448
abbrev IB_TREE_DATA_ROOT_OFF : Int := 10432
abbrev IB_USER_DATA_TO_TREE_ADDRESS_REL_OFF_IMM : Nat := 10256
abbrev INSN_DISCRIMINATOR_OFF : Nat := 0
abbrev INSN_DISCRIMINATOR_INITIALIZE : Nat := 0
abbrev INSN_DISCRIMINATOR_INSERT : Nat := 1
abbrev INSN_DISCRIMINATOR_REMOVE : Nat := 2
abbrev INSN_INSERT_KEY_OFF : Int := 1
abbrev INSN_INSERT_VALUE_OFF : Nat := 3
abbrev INSN_REMOVE_KEY_OFF : Int := 1
abbrev SF_INIT_BUMP_SEED_OFF : Int := -352
abbrev SF_INIT_SIGNER_SEED_ADDR_OFF : Int := -96
abbrev SF_INIT_SIGNER_SEED_LEN_OFF : Int := -88
abbrev SF_INIT_PDA_OFF : Int := -80
abbrev SF_INIT_CREATE_ACCOUNT_DISCRIMINATOR_UOFF : Int := -351
abbrev SF_INIT_CREATE_ACCOUNT_LAMPORTS_UOFF : Int := -347
abbrev SF_INIT_CREATE_ACCOUNT_SPACE_UOFF : Int := -339
abbrev SF_INIT_CREATE_ACCOUNT_OWNER_UOFF_0 : Int := -331
abbrev SF_INIT_CREATE_ACCOUNT_OWNER_UOFF_1 : Int := -323
abbrev SF_INIT_CREATE_ACCOUNT_OWNER_UOFF_2 : Int := -315
abbrev SF_INIT_CREATE_ACCOUNT_OWNER_UOFF_3 : Int := -307
abbrev SF_INIT_SIGNERS_SEEDS_ADDR_OFF : Int := -112
abbrev SF_INIT_SIGNERS_SEEDS_LEN_OFF : Int := -104
abbrev SF_INIT_SYSTEM_PROGRAM_ADDRESS_OFF : Int := -32
abbrev SF_INIT_INSN_PROGRAM_ID_OFF : Int := -296
abbrev SF_INIT_INSN_ACCOUNTS_OFF : Int := -288
abbrev SF_INIT_INSN_ACCOUNT_LEN_OFF : Int := -280
abbrev SF_INIT_INSN_DATA_OFF : Int := -272
abbrev SF_INIT_INSN_DATA_LEN_OFF : Int := -264
abbrev SF_INIT_USER_META_IS_WRITABLE_OFF : Int := -248
abbrev SF_INIT_TREE_META_IS_WRITABLE_OFF : Int := -232
abbrev SF_INIT_USER_INFO_IS_SIGNER_OFF : Int := -176
abbrev SF_INIT_USER_META_PUBKEY_OFF : Int := -256
abbrev SF_INIT_USER_INFO_PUBKEY_OFF : Int := -224
abbrev SF_INIT_USER_INFO_OWNER_OFF : Int := -192
abbrev SF_INIT_USER_INFO_LAMPORTS_OFF : Int := -216
abbrev SF_INIT_USER_INFO_DATA_OFF : Int := -200
abbrev SF_INIT_TREE_INFO_DATA_LEN_OFF : Int := -152
abbrev SF_INIT_TREE_INFO_IS_SIGNER_OFF : Int := -120
abbrev SF_INIT_TREE_INFO_IS_WRITABLE_UOFF : Int := -119
abbrev SF_INIT_TREE_META_PUBKEY_OFF : Int := -240
abbrev SF_INIT_TREE_INFO_PUBKEY_OFF : Int := -168
abbrev SF_INIT_TREE_INFO_OWNER_OFF : Int := -136
abbrev SF_INIT_TREE_INFO_LAMPORTS_OFF : Int := -160
abbrev SF_INIT_TREE_INFO_DATA_OFF : Int := -144
abbrev SF_INIT_PDA_TO_SYSTEM_PROGRAM_ID_REL_OFF_IMM : Nat := 48
abbrev SF_INIT_SYSTEM_PROGRAM_ID_TO_ACCT_METAS_REL_OFF_IMM : Int := -224
abbrev SF_INIT_ACCT_METAS_TO_INSN_DATA_REL_OFF_IMM : Int := -95
abbrev SF_INIT_INSN_DATA_TO_SIGNER_SEEDS_REL_OFF_IMM : Nat := 255
abbrev SF_INIT_SIGNER_SEEDS_TO_SIGNERS_SEEDS_REL_OFF_IMM : Int := -16
abbrev SF_INIT_ACCT_INFOS_OFF : Int := -224
abbrev CPI_N_ACCOUNTS : Nat := 2
abbrev CPI_N_PDA_SIGNERS : Nat := 1
abbrev CPI_N_SEEDS_CREATE_ACCOUNT : Nat := 1
abbrev CPI_N_PDA_SIGNERS_TRANSFER : Nat := 0
abbrev CPI_N_SEEDS_TRY_FIND_PDA : Nat := 0
abbrev CPI_TREE_DATA_LEN : Nat := 24
abbrev CPI_ACCOUNT_DATA_SCALAR : Nat := 152
abbrev CPI_CREATE_ACCOUNT_DISCRIMINATOR : Nat := 0
abbrev CPI_CREATE_ACCOUNT_INSN_DATA_LEN : Nat := 52
abbrev CPI_TRANSFER_DISCRIMINATOR : Nat := 2
abbrev CPI_TRANSFER_INSN_DATA_LEN : Nat := 12
abbrev CPI_WRITABLE_SIGNER : Nat := 0x101
abbrev CPI_USER_ACCOUNT_INDEX : Nat := 0
abbrev CPI_TREE_ACCOUNT_INDEX : Nat := 1
abbrev CPI_RENT_EPOCH_NULL : Nat := 0
abbrev TREE_N_CHILDREN : Nat := 2
abbrev TREE_DIR_L : Nat := 0
abbrev TREE_DIR_R : Nat := 1
abbrev TREE_COLOR_B : Nat := 0
abbrev TREE_COLOR_R : Nat := 1
abbrev TREE_HEADER_TOP_OFF : Nat := 8
abbrev TREE_HEADER_NEXT_OFF : Int := 16
abbrev TREE_DISCRIMINATOR_INSERT : Nat := 1
abbrev TREE_NODE_KEY_OFF : Int := 24
abbrev TREE_NODE_VALUE_OFF : Nat := 26
abbrev TREE_NODE_CHILD_L_OFF : Int := 8
abbrev TREE_NODE_CHILD_R_OFF : Int := 16
abbrev TREE_NODE_PARENT_OFF : Int := 0
abbrev TREE_NODE_COLOR_OFF : Int := 28

/-! ## Program (chunked lookup for O(1) simp) -/

private def progAt_0 : Nat → Option QEDGen.Solana.SBPF.Insn
  | 0 => some (.ldx .dword .r9 .r2 (-SIZE_OF_U64))  -- 0: entrypoint
  | 1 => some (.ldx .dword .r8 .r1 IB_N_ACCOUNTS_OFF)  -- 1
  | 2 => some (.ldx .byte .r7 .r2 OFFSET_ZERO)  -- 2
  | 3 => some (.jeq .r7 (.imm INSN_DISCRIMINATOR_INSERT) 114)  -- 3
  | 4 => some (.jeq .r7 (.imm INSN_DISCRIMINATOR_REMOVE) 325)  -- 4
  | 5 => some (.jeq .r7 (.imm INSN_DISCRIMINATOR_INITIALIZE) 8)  -- 5
  | 6 => some (.mov64 .r0 (.imm E_INSTRUCTION_DISCRIMINATOR))  -- 6
  | 7 => some (.exit)  -- 7
  | 8 => some (.jne .r9 (.imm SIZE_OF_INITIALIZE_INSTRUCTION) 476)  -- 8: initialize
  | 9 => some (.jne .r8 (.imm IB_N_ACCOUNTS_INIT) 478)  -- 9
  | 10 => some (.ldx .dword .r9 .r1 IB_USER_DATA_LEN_OFF)  -- 10
  | 11 => some (.jne .r9 (.imm DATA_LEN_ZERO) 496)  -- 11
  | 12 => some (.ldx .byte .r9 .r1 IB_TREE_NON_DUP_MARKER_OFF)  -- 12
  | 13 => some (.jne .r9 (.imm IB_NON_DUP_MARKER) 494)  -- 13
  | 14 => some (.ldx .dword .r9 .r1 IB_TREE_DATA_LEN_OFF)  -- 14
  | 15 => some (.jne .r9 (.imm DATA_LEN_ZERO) 492)  -- 15
  | 16 => some (.ldx .byte .r9 .r1 IB_SYSTEM_PROGRAM_NON_DUP_MARKER_OFF)  -- 16
  | 17 => some (.jne .r9 (.imm IB_NON_DUP_MARKER) 490)  -- 17
  | 18 => some (.ldx .dword .r9 .r1 IB_SYSTEM_PROGRAM_DATA_LEN_OFF)  -- 18
  | 19 => some (.jne .r9 (.imm IB_SYSTEM_PROGRAM_DATA_LEN) 488)  -- 19
  | 20 => some (.ldx .byte .r9 .r1 IB_RENT_NON_DUP_MARKER_OFF)  -- 20
  | 21 => some (.jne .r9 (.imm IB_NON_DUP_MARKER) 486)  -- 21
  | 22 => some (.ldx .dword .r9 .r1 IB_RENT_ADDRESS_OFF_0)  -- 22
  | 23 => some (.lddw .r8 IB_RENT_ID_CHUNK_0)  -- 23
  | 24 => some (.jne .r9 (.reg .r8) 484)  -- 24
  | 25 => some (.ldx .dword .r9 .r1 IB_RENT_ADDRESS_OFF_1)  -- 25
  | 26 => some (.lddw .r8 IB_RENT_ID_CHUNK_1)  -- 26
  | 27 => some (.jne .r9 (.reg .r8) 484)  -- 27
  | 28 => some (.ldx .dword .r9 .r1 IB_RENT_ADDRESS_OFF_2)  -- 28
  | 29 => some (.lddw .r8 IB_RENT_ID_CHUNK_2)  -- 29
  | 30 => some (.jne .r9 (.reg .r8) 484)  -- 30
  | 31 => some (.ldx .dword .r9 .r1 IB_RENT_ADDRESS_OFF_3)  -- 31
  | 32 => some (.mov32 .r8 (.imm IB_RENT_ID_CHUNK_3_LO))  -- 32
  | 33 => some (.jne .r9 (.reg .r8) 484)  -- 33
  | 34 => some (.mov64 .r2 (.imm CPI_N_SEEDS_TRY_FIND_PDA))  -- 34
  | 35 => some (.mov64 .r3 (.reg .r1))  -- 35
  | 36 => some (.add64 .r3 (.imm IB_INIT_PROGRAM_ID_OFF_IMM))  -- 36
  | 37 => some (.mov64 .r4 (.reg .r10))  -- 37
  | 38 => some (.add64 .r4 (.imm SF_INIT_PDA_OFF))  -- 38
  | 39 => some (.mov64 .r5 (.reg .r10))  -- 39
  | 40 => some (.add64 .r5 (.imm SF_INIT_BUMP_SEED_OFF))  -- 40
  | 41 => some (.call .sol_try_find_program_address)  -- 41
  | 42 => some (.ldx .dword .r9 .r1 IB_TREE_ADDRESS_OFF_0)  -- 42
  | 43 => some (.ldx .dword .r8 .r4 PUBKEY_CHUNK_OFF_0)  -- 43
  | 44 => some (.jne .r9 (.reg .r8) 482)  -- 44
  | 45 => some (.ldx .dword .r9 .r1 IB_TREE_ADDRESS_OFF_1)  -- 45
  | 46 => some (.ldx .dword .r8 .r4 PUBKEY_CHUNK_OFF_1)  -- 46
  | 47 => some (.jne .r9 (.reg .r8) 482)  -- 47
  | 48 => some (.ldx .dword .r9 .r1 IB_TREE_ADDRESS_OFF_2)  -- 48
  | 49 => some (.ldx .dword .r8 .r4 PUBKEY_CHUNK_OFF_2)  -- 49
  | 50 => some (.jne .r9 (.reg .r8) 482)  -- 50
  | 51 => some (.ldx .dword .r9 .r1 IB_TREE_ADDRESS_OFF_3)  -- 51
  | 52 => some (.ldx .dword .r8 .r4 PUBKEY_CHUNK_OFF_3)  -- 52
  | 53 => some (.jne .r9 (.reg .r8) 482)  -- 53
  | 54 => some (.st .dword .r10 SF_INIT_INSN_ACCOUNT_LEN_OFF CPI_N_ACCOUNTS)  -- 54
  | 55 => some (.st .dword .r10 SF_INIT_INSN_DATA_LEN_OFF CPI_CREATE_ACCOUNT_INSN_DATA_LEN)  -- 55
  | 56 => some (.ldx .dword .r9 .r1 IB_RENT_DATA_OFF)  -- 56
  | 57 => some (.mul64 .r9 (.imm CPI_ACCOUNT_DATA_SCALAR))  -- 57
  | 58 => some (.stx .dword .r10 SF_INIT_CREATE_ACCOUNT_LAMPORTS_UOFF .r9)  -- 58
  | 59 => some (.st .dword .r10 SF_INIT_CREATE_ACCOUNT_SPACE_UOFF CPI_TREE_DATA_LEN)  -- 59
  | 60 => some (.ldx .dword .r9 .r3 PUBKEY_CHUNK_OFF_0)  -- 60
  | 61 => some (.stx .dword .r10 SF_INIT_CREATE_ACCOUNT_OWNER_UOFF_0 .r9)  -- 61
  | 62 => some (.ldx .dword .r9 .r3 PUBKEY_CHUNK_OFF_1)  -- 62
  | 63 => some (.stx .dword .r10 SF_INIT_CREATE_ACCOUNT_OWNER_UOFF_1 .r9)  -- 63
  | 64 => some (.ldx .dword .r9 .r3 PUBKEY_CHUNK_OFF_2)  -- 64
  | 65 => some (.stx .dword .r10 SF_INIT_CREATE_ACCOUNT_OWNER_UOFF_2 .r9)  -- 65
  | 66 => some (.ldx .dword .r9 .r3 PUBKEY_CHUNK_OFF_3)  -- 66
  | 67 => some (.stx .dword .r10 SF_INIT_CREATE_ACCOUNT_OWNER_UOFF_3 .r9)  -- 67
  | 68 => some (.st .half .r10 SF_INIT_USER_META_IS_WRITABLE_OFF CPI_WRITABLE_SIGNER)  -- 68
  | 69 => some (.st .half .r10 SF_INIT_TREE_META_IS_WRITABLE_OFF CPI_WRITABLE_SIGNER)  -- 69
  | 70 => some (.st .half .r10 SF_INIT_USER_INFO_IS_SIGNER_OFF CPI_WRITABLE_SIGNER)  -- 70
  | 71 => some (.st .half .r10 SF_INIT_TREE_INFO_IS_SIGNER_OFF CPI_WRITABLE_SIGNER)  -- 71
  | 72 => some (.stx .dword .r10 SF_INIT_SIGNER_SEED_ADDR_OFF .r5)  -- 72
  | 73 => some (.st .dword .r10 SF_INIT_SIGNER_SEED_LEN_OFF SIZE_OF_U8)  -- 73
  | 74 => some (.st .dword .r10 SF_INIT_SIGNERS_SEEDS_LEN_OFF CPI_N_SEEDS_CREATE_ACCOUNT)  -- 74
  | 75 => some (.add64 .r1 (.imm IB_USER_ADDRESS_OFF))  -- 75
  | 76 => some (.stx .dword .r10 SF_INIT_USER_META_PUBKEY_OFF .r1)  -- 76
  | 77 => some (.stx .dword .r10 SF_INIT_USER_INFO_PUBKEY_OFF .r1)  -- 77
  | 78 => some (.add64 .r1 (.imm SIZE_OF_ADDRESS))  -- 78
  | 79 => some (.stx .dword .r10 SF_INIT_USER_INFO_OWNER_OFF .r1)  -- 79
  | 80 => some (.add64 .r1 (.imm SIZE_OF_ADDRESS))  -- 80
  | 81 => some (.stx .dword .r10 SF_INIT_USER_INFO_LAMPORTS_OFF .r1)  -- 81
  | 82 => some (.add64 .r1 (.imm SIZE_OF_U128))  -- 82
  | 83 => some (.stx .dword .r10 SF_INIT_USER_INFO_DATA_OFF .r1)  -- 83
  | 84 => some (.add64 .r1 (.imm IB_USER_DATA_TO_TREE_ADDRESS_REL_OFF_IMM))  -- 84
  | 85 => some (.stx .dword .r10 SF_INIT_TREE_META_PUBKEY_OFF .r1)  -- 85
  | 86 => some (.stx .dword .r10 SF_INIT_TREE_INFO_PUBKEY_OFF .r1)  -- 86
  | 87 => some (.add64 .r1 (.imm SIZE_OF_ADDRESS))  -- 87
  | 88 => some (.stx .dword .r10 SF_INIT_TREE_INFO_OWNER_OFF .r1)  -- 88
  | 89 => some (.add64 .r1 (.imm SIZE_OF_ADDRESS))  -- 89
  | 90 => some (.stx .dword .r10 SF_INIT_TREE_INFO_LAMPORTS_OFF .r1)  -- 90
  | 91 => some (.add64 .r1 (.imm SIZE_OF_U128))  -- 91
  | 92 => some (.stx .dword .r10 SF_INIT_TREE_INFO_DATA_OFF .r1)  -- 92
  | 93 => some (.mov64 .r6 (.reg .r1))  -- 93
  | 94 => some (.add64 .r4 (.imm SF_INIT_PDA_TO_SYSTEM_PROGRAM_ID_REL_OFF_IMM))  -- 94
  | 95 => some (.stx .dword .r10 SF_INIT_INSN_PROGRAM_ID_OFF .r4)  -- 95
  | 96 => some (.add64 .r4 (.imm SF_INIT_SYSTEM_PROGRAM_ID_TO_ACCT_METAS_REL_OFF_IMM))  -- 96
  | 97 => some (.stx .dword .r10 SF_INIT_INSN_ACCOUNTS_OFF .r4)  -- 97
  | 98 => some (.add64 .r4 (.imm SF_INIT_ACCT_METAS_TO_INSN_DATA_REL_OFF_IMM))  -- 98
  | 99 => some (.stx .dword .r10 SF_INIT_INSN_DATA_OFF .r4)  -- 99
  | _ => none

private def progAt_1 : Nat → Option QEDGen.Solana.SBPF.Insn
  | 100 => some (.add64 .r4 (.imm SF_INIT_INSN_DATA_TO_SIGNER_SEEDS_REL_OFF_IMM))  -- 100
  | 101 => some (.stx .dword .r10 SF_INIT_SIGNERS_SEEDS_ADDR_OFF .r4)  -- 101
  | 102 => some (.add64 .r4 (.imm SF_INIT_SIGNER_SEEDS_TO_SIGNERS_SEEDS_REL_OFF_IMM))  -- 102
  | 103 => some (.mov64 .r1 (.reg .r10))  -- 103
  | 104 => some (.add64 .r1 (.imm SF_INIT_INSN_PROGRAM_ID_OFF))  -- 104
  | 105 => some (.mov64 .r2 (.reg .r10))  -- 105
  | 106 => some (.add64 .r2 (.imm SF_INIT_ACCT_INFOS_OFF))  -- 106
  | 107 => some (.mov64 .r3 (.imm CPI_N_ACCOUNTS))  -- 107
  | 108 => some (.mov64 .r5 (.imm CPI_N_PDA_SIGNERS))  -- 108
  | 109 => some (.call .sol_invoke_signed_c)  -- 109
  | 110 => some (.mov64 .r7 (.reg .r6))  -- 110
  | 111 => some (.add64 .r7 (.imm SIZE_OF_TREE_HEADER))  -- 111
  | 112 => some (.stx .dword .r6 TREE_HEADER_NEXT_OFF .r7)  -- 112
  | 113 => some (.exit)  -- 113
  | 114 => some (.jne .r9 (.imm SIZE_OF_INSERT_INSTRUCTION) 476)  -- 114: insert
  | 115 => some (.jlt .r8 (.imm IB_N_ACCOUNTS_GENERAL) 478)  -- 115
  | 116 => some (.ldx .dword .r9 .r1 IB_USER_DATA_LEN_OFF)  -- 116
  | 117 => some (.jne .r9 (.imm DATA_LEN_ZERO) 496)  -- 117
  | 118 => some (.ldx .byte .r9 .r1 IB_TREE_NON_DUP_MARKER_OFF)  -- 118
  | 119 => some (.jne .r9 (.imm IB_NON_DUP_MARKER) 494)  -- 119
  | 120 => some (.ldx .dword .r9 .r1 IB_TREE_DATA_TOP_OFF)  -- 120
  | 121 => some (.jne .r9 (.imm NULL) 200)  -- 121
  | 122 => some (.jne .r8 (.imm IB_N_ACCOUNTS_INIT) 480)  -- 122: insert_allocate
  | 123 => some (.ldx .dword .r9 .r1 IB_TREE_DATA_LEN_OFF)  -- 123
  | 124 => some (.stx .dword .r10 SF_INIT_TREE_INFO_DATA_LEN_OFF .r9)  -- 124
  | 125 => some (.mov64 .r7 (.reg .r9))  -- 125
  | 126 => some (.add64 .r9 (.imm MAX_DATA_PAD))  -- 126
  | 127 => some (.and64 .r9 (.imm DATA_LEN_AND_MASK))  -- 127
  | 128 => some (.add64 .r9 (.reg .r1))  -- 128
  | 129 => some (.ldx .byte .r8 .r9 IB_SYSTEM_PROGRAM_NON_DUP_MARKER_OFF)  -- 129
  | 130 => some (.jne .r8 (.imm IB_NON_DUP_MARKER) 490)  -- 130
  | 131 => some (.ldx .dword .r8 .r9 IB_SYSTEM_PROGRAM_DATA_LEN_OFF)  -- 131
  | 132 => some (.jne .r8 (.imm IB_SYSTEM_PROGRAM_DATA_LEN) 488)  -- 132
  | 133 => some (.ldx .byte .r8 .r9 IB_RENT_NON_DUP_MARKER_OFF)  -- 133
  | 134 => some (.jne .r8 (.imm IB_NON_DUP_MARKER) 486)  -- 134
  | 135 => some (.ldx .dword .r8 .r9 IB_RENT_ADDRESS_OFF_0)  -- 135
  | 136 => some (.lddw .r4 IB_RENT_ID_CHUNK_0)  -- 136
  | 137 => some (.jne .r8 (.reg .r4) 484)  -- 137
  | 138 => some (.ldx .dword .r8 .r9 IB_RENT_ADDRESS_OFF_1)  -- 138
  | 139 => some (.lddw .r4 IB_RENT_ID_CHUNK_1)  -- 139
  | 140 => some (.jne .r8 (.reg .r4) 484)  -- 140
  | 141 => some (.ldx .dword .r8 .r9 IB_RENT_ADDRESS_OFF_2)  -- 141
  | 142 => some (.lddw .r4 IB_RENT_ID_CHUNK_2)  -- 142
  | 143 => some (.jne .r8 (.reg .r4) 484)  -- 143
  | 144 => some (.ldx .dword .r8 .r9 IB_RENT_ADDRESS_OFF_3)  -- 144
  | 145 => some (.mov32 .r4 (.imm IB_RENT_ID_CHUNK_3_LO))  -- 145
  | 146 => some (.jne .r8 (.reg .r4) 484)  -- 146
  | 147 => some (.ldx .dword .r8 .r9 IB_RENT_DATA_OFF)  -- 147
  | 148 => some (.mul64 .r8 (.imm SIZE_OF_TREE_NODE))  -- 148
  | 149 => some (.st .word .r10 SF_INIT_CREATE_ACCOUNT_DISCRIMINATOR_UOFF CPI_TRANSFER_DISCRIMINATOR)  -- 149
  | 150 => some (.stx .dword .r10 SF_INIT_CREATE_ACCOUNT_LAMPORTS_UOFF .r8)  -- 150
  | 151 => some (.st .dword .r10 SF_INIT_INSN_ACCOUNT_LEN_OFF CPI_N_ACCOUNTS)  -- 151
  | 152 => some (.st .dword .r10 SF_INIT_INSN_DATA_LEN_OFF CPI_TRANSFER_INSN_DATA_LEN)  -- 152
  | 153 => some (.st .half .r10 SF_INIT_USER_META_IS_WRITABLE_OFF CPI_WRITABLE_SIGNER)  -- 153
  | 154 => some (.st .byte .r10 SF_INIT_TREE_META_IS_WRITABLE_OFF BOOL_TRUE)  -- 154
  | 155 => some (.st .half .r10 SF_INIT_USER_INFO_IS_SIGNER_OFF CPI_WRITABLE_SIGNER)  -- 155
  | 156 => some (.st .byte .r10 SF_INIT_TREE_INFO_IS_WRITABLE_UOFF BOOL_TRUE)  -- 156
  | 157 => some (.mov64 .r6 (.reg .r1))  -- 157
  | 158 => some (.add64 .r1 (.imm IB_USER_ADDRESS_OFF))  -- 158
  | 159 => some (.stx .dword .r10 SF_INIT_USER_META_PUBKEY_OFF .r1)  -- 159
  | 160 => some (.stx .dword .r10 SF_INIT_USER_INFO_PUBKEY_OFF .r1)  -- 160
  | 161 => some (.add64 .r1 (.imm SIZE_OF_ADDRESS))  -- 161
  | 162 => some (.stx .dword .r10 SF_INIT_USER_INFO_OWNER_OFF .r1)  -- 162
  | 163 => some (.add64 .r1 (.imm SIZE_OF_ADDRESS))  -- 163
  | 164 => some (.stx .dword .r10 SF_INIT_USER_INFO_LAMPORTS_OFF .r1)  -- 164
  | 165 => some (.add64 .r1 (.imm SIZE_OF_U128))  -- 165
  | 166 => some (.stx .dword .r10 SF_INIT_USER_INFO_DATA_OFF .r1)  -- 166
  | 167 => some (.add64 .r1 (.imm IB_USER_DATA_TO_TREE_ADDRESS_REL_OFF_IMM))  -- 167
  | 168 => some (.stx .dword .r10 SF_INIT_TREE_META_PUBKEY_OFF .r1)  -- 168
  | 169 => some (.stx .dword .r10 SF_INIT_TREE_INFO_PUBKEY_OFF .r1)  -- 169
  | 170 => some (.add64 .r1 (.imm SIZE_OF_ADDRESS))  -- 170
  | 171 => some (.stx .dword .r10 SF_INIT_TREE_INFO_OWNER_OFF .r1)  -- 171
  | 172 => some (.add64 .r1 (.imm SIZE_OF_ADDRESS))  -- 172
  | 173 => some (.stx .dword .r10 SF_INIT_TREE_INFO_LAMPORTS_OFF .r1)  -- 173
  | 174 => some (.add64 .r1 (.imm SIZE_OF_U128))  -- 174
  | 175 => some (.stx .dword .r10 SF_INIT_TREE_INFO_DATA_OFF .r1)  -- 175
  | 176 => some (.mov64 .r4 (.reg .r10))  -- 176
  | 177 => some (.add64 .r4 (.imm SF_INIT_SYSTEM_PROGRAM_ADDRESS_OFF))  -- 177
  | 178 => some (.stx .dword .r10 SF_INIT_INSN_PROGRAM_ID_OFF .r4)  -- 178
  | 179 => some (.add64 .r4 (.imm SF_INIT_SYSTEM_PROGRAM_ID_TO_ACCT_METAS_REL_OFF_IMM))  -- 179
  | 180 => some (.stx .dword .r10 SF_INIT_INSN_ACCOUNTS_OFF .r4)  -- 180
  | 181 => some (.add64 .r4 (.imm SF_INIT_ACCT_METAS_TO_INSN_DATA_REL_OFF_IMM))  -- 181
  | 182 => some (.stx .dword .r10 SF_INIT_INSN_DATA_OFF .r4)  -- 182
  | 183 => some (.mov64 .r1 (.reg .r10))  -- 183
  | 184 => some (.add64 .r1 (.imm SF_INIT_INSN_PROGRAM_ID_OFF))  -- 184
  | 185 => some (.mov64 .r8 (.reg .r2))  -- 185
  | 186 => some (.mov64 .r2 (.reg .r10))  -- 186
  | 187 => some (.add64 .r2 (.imm SF_INIT_ACCT_INFOS_OFF))  -- 187
  | 188 => some (.mov64 .r3 (.imm CPI_N_ACCOUNTS))  -- 188
  | 189 => some (.mov64 .r5 (.imm CPI_N_PDA_SIGNERS_TRANSFER))  -- 189
  | 190 => some (.call .sol_invoke_signed_c)  -- 190
  | 191 => some (.mov64 .r2 (.reg .r8))  -- 191
  | 192 => some (.mov64 .r1 (.reg .r6))  -- 192
  | 193 => some (.add64 .r7 (.imm SIZE_OF_TREE_NODE))  -- 193
  | 194 => some (.stx .dword .r1 IB_TREE_DATA_LEN_OFF .r7)  -- 194
  | 195 => some (.ldx .dword .r7 .r1 IB_TREE_DATA_NEXT_OFF)  -- 195
  | 196 => some (.mov64 .r9 (.reg .r7))  -- 196
  | 197 => some (.add64 .r7 (.imm SIZE_OF_TREE_NODE))  -- 197
  | 198 => some (.stx .dword .r1 IB_TREE_DATA_NEXT_OFF .r7)  -- 198
  | 199 => some (.ja 202)  -- 199
  | _ => none

private def progAt_2 : Nat → Option QEDGen.Solana.SBPF.Insn
  | 200 => some (.ldx .dword .r8 .r9 OFFSET_ZERO)  -- 200: insert_pop
  | 201 => some (.stx .dword .r1 IB_TREE_DATA_TOP_OFF .r8)  -- 201
  | 202 => some (.ldx .word .r4 .r2 INSN_INSERT_KEY_OFF)  -- 202: insert_store_key_value_pair
  | 203 => some (.stx .word .r9 TREE_NODE_KEY_OFF .r4)  -- 203
  | 204 => some (.ldx .half .r4 .r2 INSN_INSERT_KEY_OFF)  -- 204: insert_search
  | 205 => some (.ldx .dword .r3 .r1 IB_TREE_DATA_ROOT_OFF)  -- 205
  | 206 => some (.jeq .r3 (.imm NULL) 213)  -- 206
  | 207 => some (.mov64 .r2 (.reg .r3))  -- 207: insert_search_loop
  | 208 => some (.ldx .half .r5 .r3 TREE_NODE_KEY_OFF)  -- 208
  | 209 => some (.jlt .r4 (.reg .r5) 218)  -- 209
  | 210 => some (.jgt .r4 (.reg .r5) 226)  -- 210
  | 211 => some (.mov64 .r0 (.imm E_KEY_EXISTS))  -- 211
  | 212 => some (.exit)  -- 212
  | 213 => some (.st .byte .r9 TREE_NODE_COLOR_OFF TREE_COLOR_R)  -- 213: insert_root
  | 214 => some (.mov64 .r2 (.imm NULL))  -- 214
  | 215 => some (.stx .dword .r9 TREE_NODE_PARENT_OFF .r2)  -- 215
  | 216 => some (.stx .dword .r1 IB_TREE_DATA_ROOT_OFF .r9)  -- 216
  | 217 => some (.exit)  -- 217
  | 218 => some (.ldx .dword .r3 .r2 TREE_NODE_CHILD_L_OFF)  -- 218: insert_search_branch_l
  | 219 => some (.jne .r3 (.imm NULL) 207)  -- 219
  | 220 => some (.st .byte .r9 TREE_NODE_COLOR_OFF TREE_COLOR_R)  -- 220
  | 221 => some (.stx .dword .r9 TREE_NODE_PARENT_OFF .r2)  -- 221
  | 222 => some (.stx .dword .r2 TREE_NODE_CHILD_L_OFF .r9)  -- 222
  | 223 => some (.ldx .byte .r6 .r2 TREE_NODE_COLOR_OFF)  -- 223
  | 224 => some (.jne .r6 (.imm TREE_COLOR_B) 234)  -- 224
  | 225 => some (.exit)  -- 225
  | 226 => some (.ldx .dword .r3 .r2 TREE_NODE_CHILD_R_OFF)  -- 226: insert_search_branch_r
  | 227 => some (.jne .r3 (.imm NULL) 207)  -- 227
  | 228 => some (.st .byte .r9 TREE_NODE_COLOR_OFF TREE_COLOR_R)  -- 228
  | 229 => some (.stx .dword .r9 TREE_NODE_PARENT_OFF .r2)  -- 229
  | 230 => some (.stx .dword .r2 TREE_NODE_CHILD_R_OFF .r9)  -- 230
  | 231 => some (.ldx .byte .r6 .r2 TREE_NODE_COLOR_OFF)  -- 231: insert_fixup_main
  | 232 => some (.jne .r6 (.imm TREE_COLOR_B) 234)  -- 232
  | 233 => some (.exit)  -- 233
  | 234 => some (.ldx .dword .r3 .r2 TREE_NODE_PARENT_OFF)  -- 234: insert_fixup_check_case_4
  | 235 => some (.jne .r3 (.imm NULL) 238)  -- 235
  | 236 => some (.st .byte .r2 TREE_NODE_COLOR_OFF TREE_COLOR_B)  -- 236
  | 237 => some (.exit)  -- 237
  | 238 => some (.ldx .half .r4 .r3 TREE_NODE_KEY_OFF)  -- 238: insert_fixup_check_case_5_6
  | 239 => some (.jgt .r5 (.reg .r4) 279)  -- 239
  | 240 => some (.ldx .dword .r7 .r3 TREE_NODE_CHILD_R_OFF)  -- 240: insert_fixup_check_case_5_6_dir_l
  | 241 => some (.jeq .r7 (.imm NULL) 244)  -- 241
  | 242 => some (.ldx .byte .r8 .r7 TREE_NODE_COLOR_OFF)  -- 242
  | 243 => some (.jne .r8 (.imm TREE_COLOR_B) 318)  -- 243
  | 244 => some (.ldx .dword .r6 .r2 TREE_NODE_CHILD_R_OFF)  -- 244: insert_fixup_case_5_6_dir_l
  | 245 => some (.jne .r9 (.reg .r6) 256)  -- 245
  | 246 => some (.ldx .dword .r8 .r6 TREE_NODE_CHILD_L_OFF)  -- 246: insert_fixup_case_5_dir_l
  | 247 => some (.stx .dword .r2 TREE_NODE_CHILD_R_OFF .r8)  -- 247
  | 248 => some (.jeq .r8 (.imm NULL) 250)  -- 248
  | 249 => some (.stx .dword .r8 TREE_NODE_PARENT_OFF .r2)  -- 249
  | 250 => some (.stx .dword .r6 TREE_NODE_CHILD_L_OFF .r2)  -- 250: insert_fixup_case_5_dir_l_skip
  | 251 => some (.stx .dword .r6 TREE_NODE_PARENT_OFF .r3)  -- 251
  | 252 => some (.stx .dword .r2 TREE_NODE_PARENT_OFF .r6)  -- 252
  | 253 => some (.stx .dword .r3 TREE_NODE_CHILD_L_OFF .r6)  -- 253
  | 254 => some (.mov64 .r9 (.reg .r2))  -- 254
  | 255 => some (.mov64 .r2 (.reg .r6))  -- 255
  | 256 => some (.ldx .dword .r4 .r3 TREE_NODE_PARENT_OFF)  -- 256: insert_fixup_case_6_dir_l
  | 257 => some (.ldx .dword .r8 .r2 TREE_NODE_CHILD_R_OFF)  -- 257
  | 258 => some (.stx .dword .r3 TREE_NODE_CHILD_L_OFF .r8)  -- 258
  | 259 => some (.jeq .r8 (.imm NULL) 261)  -- 259
  | 260 => some (.stx .dword .r8 TREE_NODE_PARENT_OFF .r3)  -- 260
  | 261 => some (.stx .dword .r2 TREE_NODE_CHILD_R_OFF .r3)  -- 261: insert_fixup_case_6_dir_l_skip
  | 262 => some (.stx .dword .r2 TREE_NODE_PARENT_OFF .r4)  -- 262
  | 263 => some (.stx .dword .r3 TREE_NODE_PARENT_OFF .r2)  -- 263
  | 264 => some (.jeq .r4 (.imm NULL) 275)  -- 264
  | 265 => some (.ldx .dword .r8 .r4 TREE_NODE_CHILD_R_OFF)  -- 265
  | 266 => some (.jne .r3 (.reg .r8) 271)  -- 266
  | 267 => some (.stx .dword .r4 TREE_NODE_CHILD_R_OFF .r2)  -- 267
  | 268 => some (.st .byte .r2 TREE_NODE_COLOR_OFF TREE_COLOR_B)  -- 268
  | 269 => some (.st .byte .r3 TREE_NODE_COLOR_OFF TREE_COLOR_R)  -- 269
  | 270 => some (.exit)  -- 270
  | 271 => some (.stx .dword .r4 TREE_NODE_CHILD_L_OFF .r2)  -- 271: insert_fixup_case_6_dir_l_left
  | 272 => some (.st .byte .r2 TREE_NODE_COLOR_OFF TREE_COLOR_B)  -- 272
  | 273 => some (.st .byte .r3 TREE_NODE_COLOR_OFF TREE_COLOR_R)  -- 273
  | 274 => some (.exit)  -- 274
  | 275 => some (.stx .dword .r1 IB_TREE_DATA_ROOT_OFF .r2)  -- 275: insert_fixup_case_6_dir_l_root
  | 276 => some (.st .byte .r2 TREE_NODE_COLOR_OFF TREE_COLOR_B)  -- 276
  | 277 => some (.st .byte .r3 TREE_NODE_COLOR_OFF TREE_COLOR_R)  -- 277
  | 278 => some (.exit)  -- 278
  | 279 => some (.ldx .dword .r7 .r3 TREE_NODE_CHILD_L_OFF)  -- 279: insert_fixup_check_case_5_6_dir_r
  | 280 => some (.jeq .r7 (.imm NULL) 283)  -- 280
  | 281 => some (.ldx .byte .r8 .r7 TREE_NODE_COLOR_OFF)  -- 281
  | 282 => some (.jne .r8 (.imm TREE_COLOR_B) 318)  -- 282
  | 283 => some (.ldx .dword .r6 .r2 TREE_NODE_CHILD_L_OFF)  -- 283: insert_fixup_case_5_6_dir_r
  | 284 => some (.jne .r9 (.reg .r6) 295)  -- 284
  | 285 => some (.ldx .dword .r8 .r6 TREE_NODE_CHILD_R_OFF)  -- 285: insert_fixup_case_5_dir_r
  | 286 => some (.stx .dword .r2 TREE_NODE_CHILD_L_OFF .r8)  -- 286
  | 287 => some (.jeq .r8 (.imm NULL) 289)  -- 287
  | 288 => some (.stx .dword .r8 TREE_NODE_PARENT_OFF .r2)  -- 288
  | 289 => some (.stx .dword .r6 TREE_NODE_CHILD_R_OFF .r2)  -- 289: insert_fixup_case_5_dir_r_skip
  | 290 => some (.stx .dword .r6 TREE_NODE_PARENT_OFF .r3)  -- 290
  | 291 => some (.stx .dword .r2 TREE_NODE_PARENT_OFF .r6)  -- 291
  | 292 => some (.stx .dword .r3 TREE_NODE_CHILD_R_OFF .r6)  -- 292
  | 293 => some (.mov64 .r9 (.reg .r2))  -- 293
  | 294 => some (.mov64 .r2 (.reg .r6))  -- 294
  | 295 => some (.ldx .dword .r4 .r3 TREE_NODE_PARENT_OFF)  -- 295: insert_fixup_case_6_dir_r
  | 296 => some (.ldx .dword .r8 .r2 TREE_NODE_CHILD_L_OFF)  -- 296
  | 297 => some (.stx .dword .r3 TREE_NODE_CHILD_R_OFF .r8)  -- 297
  | 298 => some (.jeq .r8 (.imm NULL) 300)  -- 298
  | 299 => some (.stx .dword .r8 TREE_NODE_PARENT_OFF .r3)  -- 299
  | _ => none

private def progAt_3 : Nat → Option QEDGen.Solana.SBPF.Insn
  | 300 => some (.stx .dword .r2 TREE_NODE_CHILD_L_OFF .r3)  -- 300: insert_fixup_case_6_dir_r_skip
  | 301 => some (.stx .dword .r2 TREE_NODE_PARENT_OFF .r4)  -- 301
  | 302 => some (.stx .dword .r3 TREE_NODE_PARENT_OFF .r2)  -- 302
  | 303 => some (.jeq .r4 (.imm NULL) 314)  -- 303
  | 304 => some (.ldx .dword .r8 .r4 TREE_NODE_CHILD_R_OFF)  -- 304
  | 305 => some (.jne .r3 (.reg .r8) 310)  -- 305
  | 306 => some (.stx .dword .r4 TREE_NODE_CHILD_R_OFF .r2)  -- 306
  | 307 => some (.st .byte .r2 TREE_NODE_COLOR_OFF TREE_COLOR_B)  -- 307
  | 308 => some (.st .byte .r3 TREE_NODE_COLOR_OFF TREE_COLOR_R)  -- 308
  | 309 => some (.exit)  -- 309
  | 310 => some (.stx .dword .r4 TREE_NODE_CHILD_L_OFF .r2)  -- 310: insert_fixup_case_6_dir_r_left
  | 311 => some (.st .byte .r2 TREE_NODE_COLOR_OFF TREE_COLOR_B)  -- 311
  | 312 => some (.st .byte .r3 TREE_NODE_COLOR_OFF TREE_COLOR_R)  -- 312
  | 313 => some (.exit)  -- 313
  | 314 => some (.stx .dword .r1 IB_TREE_DATA_ROOT_OFF .r2)  -- 314: insert_fixup_case_6_dir_r_root
  | 315 => some (.st .byte .r2 TREE_NODE_COLOR_OFF TREE_COLOR_B)  -- 315
  | 316 => some (.st .byte .r3 TREE_NODE_COLOR_OFF TREE_COLOR_R)  -- 316
  | 317 => some (.exit)  -- 317
  | 318 => some (.st .byte .r2 TREE_NODE_COLOR_OFF TREE_COLOR_B)  -- 318: insert_fixup_case_2
  | 319 => some (.st .byte .r7 TREE_NODE_COLOR_OFF TREE_COLOR_B)  -- 319
  | 320 => some (.st .byte .r3 TREE_NODE_COLOR_OFF TREE_COLOR_R)  -- 320
  | 321 => some (.mov64 .r9 (.reg .r3))  -- 321
  | 322 => some (.ldx .dword .r2 .r9 TREE_NODE_PARENT_OFF)  -- 322
  | 323 => some (.jne .r2 (.imm NULL) 231)  -- 323
  | 324 => some (.exit)  -- 324
  | 325 => some (.jne .r9 (.imm SIZE_OF_REMOVE_INSTRUCTION) 476)  -- 325: remove
  | 326 => some (.jlt .r8 (.imm IB_N_ACCOUNTS_GENERAL) 478)  -- 326
  | 327 => some (.ldx .dword .r9 .r1 IB_USER_DATA_LEN_OFF)  -- 327
  | 328 => some (.jne .r9 (.imm DATA_LEN_ZERO) 496)  -- 328
  | 329 => some (.ldx .byte .r9 .r1 IB_TREE_NON_DUP_MARKER_OFF)  -- 329
  | 330 => some (.jne .r9 (.imm IB_NON_DUP_MARKER) 494)  -- 330
  | 331 => some (.ldx .dword .r3 .r1 IB_TREE_DATA_ROOT_OFF)  -- 331: remove_search
  | 332 => some (.jeq .r3 (.imm NULL) 343)  -- 332
  | 333 => some (.ldx .half .r4 .r2 INSN_REMOVE_KEY_OFF)  -- 333
  | 334 => some (.ldx .half .r5 .r3 TREE_NODE_KEY_OFF)  -- 334: remove_search_loop
  | 335 => some (.jeq .r4 (.reg .r5) 345)  -- 335
  | 336 => some (.jgt .r4 (.reg .r5) 341)  -- 336
  | 337 => some (.ldx .dword .r3 .r3 TREE_NODE_CHILD_L_OFF)  -- 337: remove_search_l
  | 338 => some (.jne .r3 (.imm NULL) 334)  -- 338
  | 339 => some (.mov64 .r0 (.imm E_KEY_DOES_NOT_EXIST))  -- 339
  | 340 => some (.exit)  -- 340
  | 341 => some (.ldx .dword .r3 .r3 TREE_NODE_CHILD_R_OFF)  -- 341: remove_search_r
  | 342 => some (.jne .r3 (.imm NULL) 334)  -- 342
  | 343 => some (.mov64 .r0 (.imm E_KEY_DOES_NOT_EXIST))  -- 343: e_key_does_not_exist
  | 344 => some (.exit)  -- 344
  | 345 => some (.ldx .dword .r4 .r3 TREE_NODE_CHILD_L_OFF)  -- 345: remove_found
  | 346 => some (.jeq .r4 (.imm NULL) 356)  -- 346
  | 347 => some (.ldx .dword .r5 .r3 TREE_NODE_CHILD_R_OFF)  -- 347
  | 348 => some (.jeq .r5 (.imm NULL) 358)  -- 348
  | 349 => some (.ldx .dword .r4 .r5 TREE_NODE_CHILD_L_OFF)  -- 349: remove_successor_loop
  | 350 => some (.jeq .r4 (.imm NULL) 353)  -- 350
  | 351 => some (.mov64 .r5 (.reg .r4))  -- 351
  | 352 => some (.ja 349)  -- 352
  | 353 => some (.ldx .word .r4 .r5 TREE_NODE_KEY_OFF)  -- 353: remove_successor_copy
  | 354 => some (.stx .word .r3 TREE_NODE_KEY_OFF .r4)  -- 354
  | 355 => some (.mov64 .r3 (.reg .r5))  -- 355
  | 356 => some (.ldx .dword .r4 .r3 TREE_NODE_CHILD_R_OFF)  -- 356: remove_check_child_r
  | 357 => some (.jeq .r4 (.imm NULL) 385)  -- 357
  | 358 => some (.ldx .dword .r5 .r3 TREE_NODE_PARENT_OFF)  -- 358: remove_simple_2_child_l
  | 359 => some (.stx .dword .r4 TREE_NODE_PARENT_OFF .r5)  -- 359
  | 360 => some (.st .byte .r4 TREE_NODE_COLOR_OFF TREE_COLOR_B)  -- 360
  | 361 => some (.jeq .r5 (.imm NULL) 378)  -- 361
  | 362 => some (.ldx .dword .r6 .r5 TREE_NODE_CHILD_R_OFF)  -- 362
  | 363 => some (.jne .r3 (.reg .r6) 371)  -- 363
  | 364 => some (.stx .dword .r5 TREE_NODE_CHILD_R_OFF .r4)  -- 364
  | 365 => some (.st .dword .r3 TREE_NODE_CHILD_L_OFF NULL)  -- 365
  | 366 => some (.st .dword .r3 TREE_NODE_CHILD_R_OFF NULL)  -- 366
  | 367 => some (.ldx .dword .r4 .r1 IB_TREE_DATA_TOP_OFF)  -- 367
  | 368 => some (.stx .dword .r3 TREE_NODE_PARENT_OFF .r4)  -- 368
  | 369 => some (.stx .dword .r1 IB_TREE_DATA_TOP_OFF .r3)  -- 369
  | 370 => some (.exit)  -- 370
  | 371 => some (.stx .dword .r5 TREE_NODE_CHILD_L_OFF .r4)  -- 371: remove_simple_2_dir_l
  | 372 => some (.st .dword .r3 TREE_NODE_CHILD_L_OFF NULL)  -- 372
  | 373 => some (.st .dword .r3 TREE_NODE_CHILD_R_OFF NULL)  -- 373
  | 374 => some (.ldx .dword .r4 .r1 IB_TREE_DATA_TOP_OFF)  -- 374
  | 375 => some (.stx .dword .r3 TREE_NODE_PARENT_OFF .r4)  -- 375
  | 376 => some (.stx .dword .r1 IB_TREE_DATA_TOP_OFF .r3)  -- 376
  | 377 => some (.exit)  -- 377
  | 378 => some (.stx .dword .r1 IB_TREE_DATA_ROOT_OFF .r4)  -- 378: remove_simple_2_root
  | 379 => some (.st .dword .r3 TREE_NODE_CHILD_L_OFF NULL)  -- 379
  | 380 => some (.st .dword .r3 TREE_NODE_CHILD_R_OFF NULL)  -- 380
  | 381 => some (.ldx .dword .r4 .r1 IB_TREE_DATA_TOP_OFF)  -- 381
  | 382 => some (.stx .dword .r3 TREE_NODE_PARENT_OFF .r4)  -- 382
  | 383 => some (.stx .dword .r1 IB_TREE_DATA_TOP_OFF .r3)  -- 383
  | 384 => some (.exit)  -- 384
  | 385 => some (.ldx .dword .r5 .r3 TREE_NODE_PARENT_OFF)  -- 385: remove_check_simple_3_4
  | 386 => some (.jne .r5 (.imm NULL) 394)  -- 386
  | 387 => some (.st .dword .r1 IB_TREE_DATA_ROOT_OFF NULL)  -- 387
  | 388 => some (.st .dword .r3 TREE_NODE_CHILD_L_OFF NULL)  -- 388
  | 389 => some (.st .dword .r3 TREE_NODE_CHILD_R_OFF NULL)  -- 389
  | 390 => some (.ldx .dword .r4 .r1 IB_TREE_DATA_TOP_OFF)  -- 390
  | 391 => some (.stx .dword .r3 TREE_NODE_PARENT_OFF .r4)  -- 391
  | 392 => some (.stx .dword .r1 IB_TREE_DATA_TOP_OFF .r3)  -- 392
  | 393 => some (.exit)  -- 393
  | 394 => some (.ldx .byte .r4 .r3 TREE_NODE_COLOR_OFF)  -- 394: remove_check_simple_4
  | 395 => some (.jne .r4 (.imm TREE_COLOR_R) 412)  -- 395
  | 396 => some (.ldx .dword .r4 .r5 TREE_NODE_CHILD_R_OFF)  -- 396
  | 397 => some (.jne .r3 (.reg .r4) 405)  -- 397
  | 398 => some (.st .dword .r5 TREE_NODE_CHILD_R_OFF NULL)  -- 398
  | 399 => some (.st .dword .r3 TREE_NODE_CHILD_L_OFF NULL)  -- 399
  | _ => none

private def progAt_4 : Nat → Option QEDGen.Solana.SBPF.Insn
  | 400 => some (.st .dword .r3 TREE_NODE_CHILD_R_OFF NULL)  -- 400
  | 401 => some (.ldx .dword .r4 .r1 IB_TREE_DATA_TOP_OFF)  -- 401
  | 402 => some (.stx .dword .r3 TREE_NODE_PARENT_OFF .r4)  -- 402
  | 403 => some (.stx .dword .r1 IB_TREE_DATA_TOP_OFF .r3)  -- 403
  | 404 => some (.exit)  -- 404
  | 405 => some (.st .dword .r5 TREE_NODE_CHILD_L_OFF NULL)  -- 405: remove_simple_4_dir_l
  | 406 => some (.st .dword .r3 TREE_NODE_CHILD_L_OFF NULL)  -- 406
  | 407 => some (.st .dword .r3 TREE_NODE_CHILD_R_OFF NULL)  -- 407
  | 408 => some (.ldx .dword .r4 .r1 IB_TREE_DATA_TOP_OFF)  -- 408
  | 409 => some (.stx .dword .r3 TREE_NODE_PARENT_OFF .r4)  -- 409
  | 410 => some (.stx .dword .r1 IB_TREE_DATA_TOP_OFF .r3)  -- 410
  | 411 => some (.exit)  -- 411
  | 412 => some (.mov64 .r2 (.reg .r3))  -- 412: remove_complex
  | 413 => some (.ldx .dword .r5 .r3 TREE_NODE_PARENT_OFF)  -- 413
  | 414 => some (.ldx .dword .r4 .r5 TREE_NODE_CHILD_L_OFF)  -- 414
  | 415 => some (.jne .r3 (.reg .r4) 418)  -- 415
  | 416 => some (.st .dword .r5 TREE_NODE_CHILD_L_OFF NULL)  -- 416: remove_complex_dir_l
  | 417 => some (.ja 468)  -- 417
  | 418 => some (.st .dword .r5 TREE_NODE_CHILD_R_OFF NULL)  -- 418: remove_complex_dir_r
  | 419 => some (.ldx .dword .r6 .r5 TREE_NODE_CHILD_L_OFF)  -- 419: remove_complex_loop_dir_r
  | 420 => some (.ldx .dword .r7 .r6 TREE_NODE_CHILD_L_OFF)  -- 420
  | 421 => some (.ldx .dword .r8 .r6 TREE_NODE_CHILD_R_OFF)  -- 421
  | 422 => some (.ldx .byte .r9 .r6 TREE_NODE_COLOR_OFF)  -- 422
  | 423 => some (.jeq .r9 (.imm TREE_COLOR_R) 452)  -- 423
  | 424 => some (.jeq .r7 (.imm NULL) 427)  -- 424
  | 425 => some (.ldx .byte .r9 .r7 TREE_NODE_COLOR_OFF)  -- 425
  | 426 => some (.jeq .r9 (.imm TREE_COLOR_R) 447)  -- 426
  | 427 => some (.jeq .r8 (.imm NULL) 430)  -- 427: remove_complex_loop_dir_r_check_case_5
  | 428 => some (.ldx .byte .r9 .r8 TREE_NODE_COLOR_OFF)  -- 428
  | 429 => some (.jeq .r9 (.imm TREE_COLOR_R) 443)  -- 429
  | 430 => some (.jeq .r5 (.imm NULL) 468)  -- 430: remove_complex_loop_dir_r_check_case_1
  | 431 => some (.ldx .byte .r9 .r5 TREE_NODE_COLOR_OFF)  -- 431
  | 432 => some (.jne .r9 (.imm TREE_COLOR_R) 436)  -- 432
  | 433 => some (.st .byte .r6 TREE_NODE_COLOR_OFF TREE_COLOR_R)  -- 433
  | 434 => some (.st .byte .r5 TREE_NODE_COLOR_OFF TREE_COLOR_B)  -- 434
  | 435 => some (.ja 468)  -- 435
  | 436 => some (.st .byte .r6 TREE_NODE_COLOR_OFF TREE_COLOR_R)  -- 436: remove_complex_loop_dir_r_case_2
  | 437 => some (.mov64 .r3 (.reg .r5))  -- 437
  | 438 => some (.ldx .dword .r5 .r3 TREE_NODE_PARENT_OFF)  -- 438
  | 439 => some (.jeq .r5 (.imm NULL) 443)  -- 439
  | 440 => some (.ldx .dword .r4 .r5 TREE_NODE_CHILD_L_OFF)  -- 440
  | 441 => some (.jeq .r3 (.reg .r4) 468)  -- 441
  | 442 => some (.ja 419)  -- 442
  | 443 => some (.st .byte .r6 TREE_NODE_COLOR_OFF TREE_COLOR_R)  -- 443: remove_complex_case_5_dir_r
  | 444 => some (.st .byte .r8 TREE_NODE_COLOR_OFF TREE_COLOR_B)  -- 444
  | 445 => some (.mov64 .r7 (.reg .r6))  -- 445
  | 446 => some (.mov64 .r6 (.reg .r8))  -- 446
  | 447 => some (.ldx .byte .r4 .r5 TREE_NODE_COLOR_OFF)  -- 447: remove_complex_case_6_dir_r
  | 448 => some (.stx .byte .r6 TREE_NODE_COLOR_OFF .r4)  -- 448
  | 449 => some (.st .byte .r5 TREE_NODE_COLOR_OFF TREE_COLOR_B)  -- 449
  | 450 => some (.st .byte .r7 TREE_NODE_COLOR_OFF TREE_COLOR_B)  -- 450
  | 451 => some (.ja 468)  -- 451
  | 452 => some (.st .byte .r5 TREE_NODE_COLOR_OFF TREE_COLOR_R)  -- 452: remove_complex_loop_dir_r_sibling_red
  | 453 => some (.st .byte .r6 TREE_NODE_COLOR_OFF TREE_COLOR_B)  -- 453
  | 454 => some (.mov64 .r6 (.reg .r8))  -- 454
  | 455 => some (.ldx .dword .r4 .r6 TREE_NODE_CHILD_L_OFF)  -- 455
  | 456 => some (.mov64 .r7 (.reg .r4))  -- 456
  | 457 => some (.jeq .r7 (.imm NULL) 460)  -- 457
  | 458 => some (.ldx .byte .r4 .r7 TREE_NODE_COLOR_OFF)  -- 458
  | 459 => some (.jeq .r4 (.imm TREE_COLOR_R) 447)  -- 459
  | 460 => some (.ldx .dword .r4 .r6 TREE_NODE_CHILD_R_OFF)  -- 460: remove_complex_loop_dir_r_sibling_red_check_case_5
  | 461 => some (.mov64 .r8 (.reg .r4))  -- 461
  | 462 => some (.jeq .r8 (.imm NULL) 465)  -- 462
  | 463 => some (.ldx .byte .r4 .r8 TREE_NODE_COLOR_OFF)  -- 463
  | 464 => some (.jeq .r4 (.imm TREE_COLOR_R) 443)  -- 464
  | 465 => some (.st .byte .r6 TREE_NODE_COLOR_OFF TREE_COLOR_R)  -- 465: remove_complex_loop_dir_r_sibling_red_case_4
  | 466 => some (.st .byte .r5 TREE_NODE_COLOR_OFF TREE_COLOR_B)  -- 466
  | 467 => some (.ja 468)  -- 467
  | 468 => some (.st .dword .r2 TREE_NODE_CHILD_L_OFF NULL)  -- 468: remove_complex_recycle_node
  | 469 => some (.st .dword .r2 TREE_NODE_CHILD_R_OFF NULL)  -- 469
  | 470 => some (.ldx .dword .r4 .r1 IB_TREE_DATA_TOP_OFF)  -- 470
  | 471 => some (.stx .dword .r2 TREE_NODE_PARENT_OFF .r4)  -- 471
  | 472 => some (.stx .dword .r1 IB_TREE_DATA_TOP_OFF .r2)  -- 472
  | 473 => some (.exit)  -- 473
  | 474 => some (.mov64 .r0 (.imm E_INSTRUCTION_DATA))  -- 474: e_instruction_data
  | 475 => some (.exit)  -- 475
  | 476 => some (.mov64 .r0 (.imm E_INSTRUCTION_DATA_LEN))  -- 476: e_instruction_data_len
  | 477 => some (.exit)  -- 477
  | 478 => some (.mov64 .r0 (.imm E_N_ACCOUNTS))  -- 478: e_n_accounts
  | 479 => some (.exit)  -- 479
  | 480 => some (.mov64 .r0 (.imm E_N_ACCOUNTS_INSERT_ALLOCATION))  -- 480: e_n_accounts_insert_allocation
  | 481 => some (.exit)  -- 481
  | 482 => some (.mov64 .r0 (.imm E_PDA_MISMATCH))  -- 482: e_pda_mismatch
  | 483 => some (.exit)  -- 483
  | 484 => some (.mov64 .r0 (.imm E_RENT_ADDRESS))  -- 484: e_rent_address
  | 485 => some (.exit)  -- 485
  | 486 => some (.mov64 .r0 (.imm E_RENT_DUPLICATE))  -- 486: e_rent_duplicate
  | 487 => some (.exit)  -- 487
  | 488 => some (.mov64 .r0 (.imm E_SYSTEM_PROGRAM_DATA_LEN))  -- 488: e_system_program_data_len
  | 489 => some (.exit)  -- 489
  | 490 => some (.mov64 .r0 (.imm E_SYSTEM_PROGRAM_DUPLICATE))  -- 490: e_system_program_duplicate
  | 491 => some (.exit)  -- 491
  | 492 => some (.mov64 .r0 (.imm E_TREE_DATA_LEN))  -- 492: e_tree_data_len
  | 493 => some (.exit)  -- 493
  | 494 => some (.mov64 .r0 (.imm E_TREE_DUPLICATE))  -- 494: e_tree_duplicate
  | 495 => some (.exit)  -- 495
  | 496 => some (.mov64 .r0 (.imm E_USER_DATA_LEN))  -- 496: e_user_data_len
  | 497 => some (.exit)  -- 497
  | _ => none

def progAt (n : Nat) : Option QEDGen.Solana.SBPF.Insn :=
  if n < 100 then progAt_0 n
  else
  if n < 200 then progAt_1 n
  else
  if n < 300 then progAt_2 n
  else
  if n < 400 then progAt_3 n
  else
  progAt_4 n

def prog : Program := #[
  .ldx .dword .r9 .r2 (-SIZE_OF_U64),
  .ldx .dword .r8 .r1 IB_N_ACCOUNTS_OFF,
  .ldx .byte .r7 .r2 OFFSET_ZERO,
  .jeq .r7 (.imm INSN_DISCRIMINATOR_INSERT) 114,
  .jeq .r7 (.imm INSN_DISCRIMINATOR_REMOVE) 325,
  .jeq .r7 (.imm INSN_DISCRIMINATOR_INITIALIZE) 8,
  .mov64 .r0 (.imm E_INSTRUCTION_DISCRIMINATOR),
  .exit,
  .jne .r9 (.imm SIZE_OF_INITIALIZE_INSTRUCTION) 476,
  .jne .r8 (.imm IB_N_ACCOUNTS_INIT) 478,
  .ldx .dword .r9 .r1 IB_USER_DATA_LEN_OFF,
  .jne .r9 (.imm DATA_LEN_ZERO) 496,
  .ldx .byte .r9 .r1 IB_TREE_NON_DUP_MARKER_OFF,
  .jne .r9 (.imm IB_NON_DUP_MARKER) 494,
  .ldx .dword .r9 .r1 IB_TREE_DATA_LEN_OFF,
  .jne .r9 (.imm DATA_LEN_ZERO) 492,
  .ldx .byte .r9 .r1 IB_SYSTEM_PROGRAM_NON_DUP_MARKER_OFF,
  .jne .r9 (.imm IB_NON_DUP_MARKER) 490,
  .ldx .dword .r9 .r1 IB_SYSTEM_PROGRAM_DATA_LEN_OFF,
  .jne .r9 (.imm IB_SYSTEM_PROGRAM_DATA_LEN) 488,
  .ldx .byte .r9 .r1 IB_RENT_NON_DUP_MARKER_OFF,
  .jne .r9 (.imm IB_NON_DUP_MARKER) 486,
  .ldx .dword .r9 .r1 IB_RENT_ADDRESS_OFF_0,
  .lddw .r8 IB_RENT_ID_CHUNK_0,
  .jne .r9 (.reg .r8) 484,
  .ldx .dword .r9 .r1 IB_RENT_ADDRESS_OFF_1,
  .lddw .r8 IB_RENT_ID_CHUNK_1,
  .jne .r9 (.reg .r8) 484,
  .ldx .dword .r9 .r1 IB_RENT_ADDRESS_OFF_2,
  .lddw .r8 IB_RENT_ID_CHUNK_2,
  .jne .r9 (.reg .r8) 484,
  .ldx .dword .r9 .r1 IB_RENT_ADDRESS_OFF_3,
  .mov32 .r8 (.imm IB_RENT_ID_CHUNK_3_LO),
  .jne .r9 (.reg .r8) 484,
  .mov64 .r2 (.imm CPI_N_SEEDS_TRY_FIND_PDA),
  .mov64 .r3 (.reg .r1),
  .add64 .r3 (.imm IB_INIT_PROGRAM_ID_OFF_IMM),
  .mov64 .r4 (.reg .r10),
  .add64 .r4 (.imm SF_INIT_PDA_OFF),
  .mov64 .r5 (.reg .r10),
  .add64 .r5 (.imm SF_INIT_BUMP_SEED_OFF),
  .call .sol_try_find_program_address,
  .ldx .dword .r9 .r1 IB_TREE_ADDRESS_OFF_0,
  .ldx .dword .r8 .r4 PUBKEY_CHUNK_OFF_0,
  .jne .r9 (.reg .r8) 482,
  .ldx .dword .r9 .r1 IB_TREE_ADDRESS_OFF_1,
  .ldx .dword .r8 .r4 PUBKEY_CHUNK_OFF_1,
  .jne .r9 (.reg .r8) 482,
  .ldx .dword .r9 .r1 IB_TREE_ADDRESS_OFF_2,
  .ldx .dword .r8 .r4 PUBKEY_CHUNK_OFF_2,
  .jne .r9 (.reg .r8) 482,
  .ldx .dword .r9 .r1 IB_TREE_ADDRESS_OFF_3,
  .ldx .dword .r8 .r4 PUBKEY_CHUNK_OFF_3,
  .jne .r9 (.reg .r8) 482,
  .st .dword .r10 SF_INIT_INSN_ACCOUNT_LEN_OFF CPI_N_ACCOUNTS,
  .st .dword .r10 SF_INIT_INSN_DATA_LEN_OFF CPI_CREATE_ACCOUNT_INSN_DATA_LEN,
  .ldx .dword .r9 .r1 IB_RENT_DATA_OFF,
  .mul64 .r9 (.imm CPI_ACCOUNT_DATA_SCALAR),
  .stx .dword .r10 SF_INIT_CREATE_ACCOUNT_LAMPORTS_UOFF .r9,
  .st .dword .r10 SF_INIT_CREATE_ACCOUNT_SPACE_UOFF CPI_TREE_DATA_LEN,
  .ldx .dword .r9 .r3 PUBKEY_CHUNK_OFF_0,
  .stx .dword .r10 SF_INIT_CREATE_ACCOUNT_OWNER_UOFF_0 .r9,
  .ldx .dword .r9 .r3 PUBKEY_CHUNK_OFF_1,
  .stx .dword .r10 SF_INIT_CREATE_ACCOUNT_OWNER_UOFF_1 .r9,
  .ldx .dword .r9 .r3 PUBKEY_CHUNK_OFF_2,
  .stx .dword .r10 SF_INIT_CREATE_ACCOUNT_OWNER_UOFF_2 .r9,
  .ldx .dword .r9 .r3 PUBKEY_CHUNK_OFF_3,
  .stx .dword .r10 SF_INIT_CREATE_ACCOUNT_OWNER_UOFF_3 .r9,
  .st .half .r10 SF_INIT_USER_META_IS_WRITABLE_OFF CPI_WRITABLE_SIGNER,
  .st .half .r10 SF_INIT_TREE_META_IS_WRITABLE_OFF CPI_WRITABLE_SIGNER,
  .st .half .r10 SF_INIT_USER_INFO_IS_SIGNER_OFF CPI_WRITABLE_SIGNER,
  .st .half .r10 SF_INIT_TREE_INFO_IS_SIGNER_OFF CPI_WRITABLE_SIGNER,
  .stx .dword .r10 SF_INIT_SIGNER_SEED_ADDR_OFF .r5,
  .st .dword .r10 SF_INIT_SIGNER_SEED_LEN_OFF SIZE_OF_U8,
  .st .dword .r10 SF_INIT_SIGNERS_SEEDS_LEN_OFF CPI_N_SEEDS_CREATE_ACCOUNT,
  .add64 .r1 (.imm IB_USER_ADDRESS_OFF),
  .stx .dword .r10 SF_INIT_USER_META_PUBKEY_OFF .r1,
  .stx .dword .r10 SF_INIT_USER_INFO_PUBKEY_OFF .r1,
  .add64 .r1 (.imm SIZE_OF_ADDRESS),
  .stx .dword .r10 SF_INIT_USER_INFO_OWNER_OFF .r1,
  .add64 .r1 (.imm SIZE_OF_ADDRESS),
  .stx .dword .r10 SF_INIT_USER_INFO_LAMPORTS_OFF .r1,
  .add64 .r1 (.imm SIZE_OF_U128),
  .stx .dword .r10 SF_INIT_USER_INFO_DATA_OFF .r1,
  .add64 .r1 (.imm IB_USER_DATA_TO_TREE_ADDRESS_REL_OFF_IMM),
  .stx .dword .r10 SF_INIT_TREE_META_PUBKEY_OFF .r1,
  .stx .dword .r10 SF_INIT_TREE_INFO_PUBKEY_OFF .r1,
  .add64 .r1 (.imm SIZE_OF_ADDRESS),
  .stx .dword .r10 SF_INIT_TREE_INFO_OWNER_OFF .r1,
  .add64 .r1 (.imm SIZE_OF_ADDRESS),
  .stx .dword .r10 SF_INIT_TREE_INFO_LAMPORTS_OFF .r1,
  .add64 .r1 (.imm SIZE_OF_U128),
  .stx .dword .r10 SF_INIT_TREE_INFO_DATA_OFF .r1,
  .mov64 .r6 (.reg .r1),
  .add64 .r4 (.imm SF_INIT_PDA_TO_SYSTEM_PROGRAM_ID_REL_OFF_IMM),
  .stx .dword .r10 SF_INIT_INSN_PROGRAM_ID_OFF .r4,
  .add64 .r4 (.imm SF_INIT_SYSTEM_PROGRAM_ID_TO_ACCT_METAS_REL_OFF_IMM),
  .stx .dword .r10 SF_INIT_INSN_ACCOUNTS_OFF .r4,
  .add64 .r4 (.imm SF_INIT_ACCT_METAS_TO_INSN_DATA_REL_OFF_IMM),
  .stx .dword .r10 SF_INIT_INSN_DATA_OFF .r4,
  .add64 .r4 (.imm SF_INIT_INSN_DATA_TO_SIGNER_SEEDS_REL_OFF_IMM),
  .stx .dword .r10 SF_INIT_SIGNERS_SEEDS_ADDR_OFF .r4,
  .add64 .r4 (.imm SF_INIT_SIGNER_SEEDS_TO_SIGNERS_SEEDS_REL_OFF_IMM),
  .mov64 .r1 (.reg .r10),
  .add64 .r1 (.imm SF_INIT_INSN_PROGRAM_ID_OFF),
  .mov64 .r2 (.reg .r10),
  .add64 .r2 (.imm SF_INIT_ACCT_INFOS_OFF),
  .mov64 .r3 (.imm CPI_N_ACCOUNTS),
  .mov64 .r5 (.imm CPI_N_PDA_SIGNERS),
  .call .sol_invoke_signed_c,
  .mov64 .r7 (.reg .r6),
  .add64 .r7 (.imm SIZE_OF_TREE_HEADER),
  .stx .dword .r6 TREE_HEADER_NEXT_OFF .r7,
  .exit,
  .jne .r9 (.imm SIZE_OF_INSERT_INSTRUCTION) 476,
  .jlt .r8 (.imm IB_N_ACCOUNTS_GENERAL) 478,
  .ldx .dword .r9 .r1 IB_USER_DATA_LEN_OFF,
  .jne .r9 (.imm DATA_LEN_ZERO) 496,
  .ldx .byte .r9 .r1 IB_TREE_NON_DUP_MARKER_OFF,
  .jne .r9 (.imm IB_NON_DUP_MARKER) 494,
  .ldx .dword .r9 .r1 IB_TREE_DATA_TOP_OFF,
  .jne .r9 (.imm NULL) 200,
  .jne .r8 (.imm IB_N_ACCOUNTS_INIT) 480,
  .ldx .dword .r9 .r1 IB_TREE_DATA_LEN_OFF,
  .stx .dword .r10 SF_INIT_TREE_INFO_DATA_LEN_OFF .r9,
  .mov64 .r7 (.reg .r9),
  .add64 .r9 (.imm MAX_DATA_PAD),
  .and64 .r9 (.imm DATA_LEN_AND_MASK),
  .add64 .r9 (.reg .r1),
  .ldx .byte .r8 .r9 IB_SYSTEM_PROGRAM_NON_DUP_MARKER_OFF,
  .jne .r8 (.imm IB_NON_DUP_MARKER) 490,
  .ldx .dword .r8 .r9 IB_SYSTEM_PROGRAM_DATA_LEN_OFF,
  .jne .r8 (.imm IB_SYSTEM_PROGRAM_DATA_LEN) 488,
  .ldx .byte .r8 .r9 IB_RENT_NON_DUP_MARKER_OFF,
  .jne .r8 (.imm IB_NON_DUP_MARKER) 486,
  .ldx .dword .r8 .r9 IB_RENT_ADDRESS_OFF_0,
  .lddw .r4 IB_RENT_ID_CHUNK_0,
  .jne .r8 (.reg .r4) 484,
  .ldx .dword .r8 .r9 IB_RENT_ADDRESS_OFF_1,
  .lddw .r4 IB_RENT_ID_CHUNK_1,
  .jne .r8 (.reg .r4) 484,
  .ldx .dword .r8 .r9 IB_RENT_ADDRESS_OFF_2,
  .lddw .r4 IB_RENT_ID_CHUNK_2,
  .jne .r8 (.reg .r4) 484,
  .ldx .dword .r8 .r9 IB_RENT_ADDRESS_OFF_3,
  .mov32 .r4 (.imm IB_RENT_ID_CHUNK_3_LO),
  .jne .r8 (.reg .r4) 484,
  .ldx .dword .r8 .r9 IB_RENT_DATA_OFF,
  .mul64 .r8 (.imm SIZE_OF_TREE_NODE),
  .st .word .r10 SF_INIT_CREATE_ACCOUNT_DISCRIMINATOR_UOFF CPI_TRANSFER_DISCRIMINATOR,
  .stx .dword .r10 SF_INIT_CREATE_ACCOUNT_LAMPORTS_UOFF .r8,
  .st .dword .r10 SF_INIT_INSN_ACCOUNT_LEN_OFF CPI_N_ACCOUNTS,
  .st .dword .r10 SF_INIT_INSN_DATA_LEN_OFF CPI_TRANSFER_INSN_DATA_LEN,
  .st .half .r10 SF_INIT_USER_META_IS_WRITABLE_OFF CPI_WRITABLE_SIGNER,
  .st .byte .r10 SF_INIT_TREE_META_IS_WRITABLE_OFF BOOL_TRUE,
  .st .half .r10 SF_INIT_USER_INFO_IS_SIGNER_OFF CPI_WRITABLE_SIGNER,
  .st .byte .r10 SF_INIT_TREE_INFO_IS_WRITABLE_UOFF BOOL_TRUE,
  .mov64 .r6 (.reg .r1),
  .add64 .r1 (.imm IB_USER_ADDRESS_OFF),
  .stx .dword .r10 SF_INIT_USER_META_PUBKEY_OFF .r1,
  .stx .dword .r10 SF_INIT_USER_INFO_PUBKEY_OFF .r1,
  .add64 .r1 (.imm SIZE_OF_ADDRESS),
  .stx .dword .r10 SF_INIT_USER_INFO_OWNER_OFF .r1,
  .add64 .r1 (.imm SIZE_OF_ADDRESS),
  .stx .dword .r10 SF_INIT_USER_INFO_LAMPORTS_OFF .r1,
  .add64 .r1 (.imm SIZE_OF_U128),
  .stx .dword .r10 SF_INIT_USER_INFO_DATA_OFF .r1,
  .add64 .r1 (.imm IB_USER_DATA_TO_TREE_ADDRESS_REL_OFF_IMM),
  .stx .dword .r10 SF_INIT_TREE_META_PUBKEY_OFF .r1,
  .stx .dword .r10 SF_INIT_TREE_INFO_PUBKEY_OFF .r1,
  .add64 .r1 (.imm SIZE_OF_ADDRESS),
  .stx .dword .r10 SF_INIT_TREE_INFO_OWNER_OFF .r1,
  .add64 .r1 (.imm SIZE_OF_ADDRESS),
  .stx .dword .r10 SF_INIT_TREE_INFO_LAMPORTS_OFF .r1,
  .add64 .r1 (.imm SIZE_OF_U128),
  .stx .dword .r10 SF_INIT_TREE_INFO_DATA_OFF .r1,
  .mov64 .r4 (.reg .r10),
  .add64 .r4 (.imm SF_INIT_SYSTEM_PROGRAM_ADDRESS_OFF),
  .stx .dword .r10 SF_INIT_INSN_PROGRAM_ID_OFF .r4,
  .add64 .r4 (.imm SF_INIT_SYSTEM_PROGRAM_ID_TO_ACCT_METAS_REL_OFF_IMM),
  .stx .dword .r10 SF_INIT_INSN_ACCOUNTS_OFF .r4,
  .add64 .r4 (.imm SF_INIT_ACCT_METAS_TO_INSN_DATA_REL_OFF_IMM),
  .stx .dword .r10 SF_INIT_INSN_DATA_OFF .r4,
  .mov64 .r1 (.reg .r10),
  .add64 .r1 (.imm SF_INIT_INSN_PROGRAM_ID_OFF),
  .mov64 .r8 (.reg .r2),
  .mov64 .r2 (.reg .r10),
  .add64 .r2 (.imm SF_INIT_ACCT_INFOS_OFF),
  .mov64 .r3 (.imm CPI_N_ACCOUNTS),
  .mov64 .r5 (.imm CPI_N_PDA_SIGNERS_TRANSFER),
  .call .sol_invoke_signed_c,
  .mov64 .r2 (.reg .r8),
  .mov64 .r1 (.reg .r6),
  .add64 .r7 (.imm SIZE_OF_TREE_NODE),
  .stx .dword .r1 IB_TREE_DATA_LEN_OFF .r7,
  .ldx .dword .r7 .r1 IB_TREE_DATA_NEXT_OFF,
  .mov64 .r9 (.reg .r7),
  .add64 .r7 (.imm SIZE_OF_TREE_NODE),
  .stx .dword .r1 IB_TREE_DATA_NEXT_OFF .r7,
  .ja 202,
  .ldx .dword .r8 .r9 OFFSET_ZERO,
  .stx .dword .r1 IB_TREE_DATA_TOP_OFF .r8,
  .ldx .word .r4 .r2 INSN_INSERT_KEY_OFF,
  .stx .word .r9 TREE_NODE_KEY_OFF .r4,
  .ldx .half .r4 .r2 INSN_INSERT_KEY_OFF,
  .ldx .dword .r3 .r1 IB_TREE_DATA_ROOT_OFF,
  .jeq .r3 (.imm NULL) 213,
  .mov64 .r2 (.reg .r3),
  .ldx .half .r5 .r3 TREE_NODE_KEY_OFF,
  .jlt .r4 (.reg .r5) 218,
  .jgt .r4 (.reg .r5) 226,
  .mov64 .r0 (.imm E_KEY_EXISTS),
  .exit,
  .st .byte .r9 TREE_NODE_COLOR_OFF TREE_COLOR_R,
  .mov64 .r2 (.imm NULL),
  .stx .dword .r9 TREE_NODE_PARENT_OFF .r2,
  .stx .dword .r1 IB_TREE_DATA_ROOT_OFF .r9,
  .exit,
  .ldx .dword .r3 .r2 TREE_NODE_CHILD_L_OFF,
  .jne .r3 (.imm NULL) 207,
  .st .byte .r9 TREE_NODE_COLOR_OFF TREE_COLOR_R,
  .stx .dword .r9 TREE_NODE_PARENT_OFF .r2,
  .stx .dword .r2 TREE_NODE_CHILD_L_OFF .r9,
  .ldx .byte .r6 .r2 TREE_NODE_COLOR_OFF,
  .jne .r6 (.imm TREE_COLOR_B) 234,
  .exit,
  .ldx .dword .r3 .r2 TREE_NODE_CHILD_R_OFF,
  .jne .r3 (.imm NULL) 207,
  .st .byte .r9 TREE_NODE_COLOR_OFF TREE_COLOR_R,
  .stx .dword .r9 TREE_NODE_PARENT_OFF .r2,
  .stx .dword .r2 TREE_NODE_CHILD_R_OFF .r9,
  .ldx .byte .r6 .r2 TREE_NODE_COLOR_OFF,
  .jne .r6 (.imm TREE_COLOR_B) 234,
  .exit,
  .ldx .dword .r3 .r2 TREE_NODE_PARENT_OFF,
  .jne .r3 (.imm NULL) 238,
  .st .byte .r2 TREE_NODE_COLOR_OFF TREE_COLOR_B,
  .exit,
  .ldx .half .r4 .r3 TREE_NODE_KEY_OFF,
  .jgt .r5 (.reg .r4) 279,
  .ldx .dword .r7 .r3 TREE_NODE_CHILD_R_OFF,
  .jeq .r7 (.imm NULL) 244,
  .ldx .byte .r8 .r7 TREE_NODE_COLOR_OFF,
  .jne .r8 (.imm TREE_COLOR_B) 318,
  .ldx .dword .r6 .r2 TREE_NODE_CHILD_R_OFF,
  .jne .r9 (.reg .r6) 256,
  .ldx .dword .r8 .r6 TREE_NODE_CHILD_L_OFF,
  .stx .dword .r2 TREE_NODE_CHILD_R_OFF .r8,
  .jeq .r8 (.imm NULL) 250,
  .stx .dword .r8 TREE_NODE_PARENT_OFF .r2,
  .stx .dword .r6 TREE_NODE_CHILD_L_OFF .r2,
  .stx .dword .r6 TREE_NODE_PARENT_OFF .r3,
  .stx .dword .r2 TREE_NODE_PARENT_OFF .r6,
  .stx .dword .r3 TREE_NODE_CHILD_L_OFF .r6,
  .mov64 .r9 (.reg .r2),
  .mov64 .r2 (.reg .r6),
  .ldx .dword .r4 .r3 TREE_NODE_PARENT_OFF,
  .ldx .dword .r8 .r2 TREE_NODE_CHILD_R_OFF,
  .stx .dword .r3 TREE_NODE_CHILD_L_OFF .r8,
  .jeq .r8 (.imm NULL) 261,
  .stx .dword .r8 TREE_NODE_PARENT_OFF .r3,
  .stx .dword .r2 TREE_NODE_CHILD_R_OFF .r3,
  .stx .dword .r2 TREE_NODE_PARENT_OFF .r4,
  .stx .dword .r3 TREE_NODE_PARENT_OFF .r2,
  .jeq .r4 (.imm NULL) 275,
  .ldx .dword .r8 .r4 TREE_NODE_CHILD_R_OFF,
  .jne .r3 (.reg .r8) 271,
  .stx .dword .r4 TREE_NODE_CHILD_R_OFF .r2,
  .st .byte .r2 TREE_NODE_COLOR_OFF TREE_COLOR_B,
  .st .byte .r3 TREE_NODE_COLOR_OFF TREE_COLOR_R,
  .exit,
  .stx .dword .r4 TREE_NODE_CHILD_L_OFF .r2,
  .st .byte .r2 TREE_NODE_COLOR_OFF TREE_COLOR_B,
  .st .byte .r3 TREE_NODE_COLOR_OFF TREE_COLOR_R,
  .exit,
  .stx .dword .r1 IB_TREE_DATA_ROOT_OFF .r2,
  .st .byte .r2 TREE_NODE_COLOR_OFF TREE_COLOR_B,
  .st .byte .r3 TREE_NODE_COLOR_OFF TREE_COLOR_R,
  .exit,
  .ldx .dword .r7 .r3 TREE_NODE_CHILD_L_OFF,
  .jeq .r7 (.imm NULL) 283,
  .ldx .byte .r8 .r7 TREE_NODE_COLOR_OFF,
  .jne .r8 (.imm TREE_COLOR_B) 318,
  .ldx .dword .r6 .r2 TREE_NODE_CHILD_L_OFF,
  .jne .r9 (.reg .r6) 295,
  .ldx .dword .r8 .r6 TREE_NODE_CHILD_R_OFF,
  .stx .dword .r2 TREE_NODE_CHILD_L_OFF .r8,
  .jeq .r8 (.imm NULL) 289,
  .stx .dword .r8 TREE_NODE_PARENT_OFF .r2,
  .stx .dword .r6 TREE_NODE_CHILD_R_OFF .r2,
  .stx .dword .r6 TREE_NODE_PARENT_OFF .r3,
  .stx .dword .r2 TREE_NODE_PARENT_OFF .r6,
  .stx .dword .r3 TREE_NODE_CHILD_R_OFF .r6,
  .mov64 .r9 (.reg .r2),
  .mov64 .r2 (.reg .r6),
  .ldx .dword .r4 .r3 TREE_NODE_PARENT_OFF,
  .ldx .dword .r8 .r2 TREE_NODE_CHILD_L_OFF,
  .stx .dword .r3 TREE_NODE_CHILD_R_OFF .r8,
  .jeq .r8 (.imm NULL) 300,
  .stx .dword .r8 TREE_NODE_PARENT_OFF .r3,
  .stx .dword .r2 TREE_NODE_CHILD_L_OFF .r3,
  .stx .dword .r2 TREE_NODE_PARENT_OFF .r4,
  .stx .dword .r3 TREE_NODE_PARENT_OFF .r2,
  .jeq .r4 (.imm NULL) 314,
  .ldx .dword .r8 .r4 TREE_NODE_CHILD_R_OFF,
  .jne .r3 (.reg .r8) 310,
  .stx .dword .r4 TREE_NODE_CHILD_R_OFF .r2,
  .st .byte .r2 TREE_NODE_COLOR_OFF TREE_COLOR_B,
  .st .byte .r3 TREE_NODE_COLOR_OFF TREE_COLOR_R,
  .exit,
  .stx .dword .r4 TREE_NODE_CHILD_L_OFF .r2,
  .st .byte .r2 TREE_NODE_COLOR_OFF TREE_COLOR_B,
  .st .byte .r3 TREE_NODE_COLOR_OFF TREE_COLOR_R,
  .exit,
  .stx .dword .r1 IB_TREE_DATA_ROOT_OFF .r2,
  .st .byte .r2 TREE_NODE_COLOR_OFF TREE_COLOR_B,
  .st .byte .r3 TREE_NODE_COLOR_OFF TREE_COLOR_R,
  .exit,
  .st .byte .r2 TREE_NODE_COLOR_OFF TREE_COLOR_B,
  .st .byte .r7 TREE_NODE_COLOR_OFF TREE_COLOR_B,
  .st .byte .r3 TREE_NODE_COLOR_OFF TREE_COLOR_R,
  .mov64 .r9 (.reg .r3),
  .ldx .dword .r2 .r9 TREE_NODE_PARENT_OFF,
  .jne .r2 (.imm NULL) 231,
  .exit,
  .jne .r9 (.imm SIZE_OF_REMOVE_INSTRUCTION) 476,
  .jlt .r8 (.imm IB_N_ACCOUNTS_GENERAL) 478,
  .ldx .dword .r9 .r1 IB_USER_DATA_LEN_OFF,
  .jne .r9 (.imm DATA_LEN_ZERO) 496,
  .ldx .byte .r9 .r1 IB_TREE_NON_DUP_MARKER_OFF,
  .jne .r9 (.imm IB_NON_DUP_MARKER) 494,
  .ldx .dword .r3 .r1 IB_TREE_DATA_ROOT_OFF,
  .jeq .r3 (.imm NULL) 343,
  .ldx .half .r4 .r2 INSN_REMOVE_KEY_OFF,
  .ldx .half .r5 .r3 TREE_NODE_KEY_OFF,
  .jeq .r4 (.reg .r5) 345,
  .jgt .r4 (.reg .r5) 341,
  .ldx .dword .r3 .r3 TREE_NODE_CHILD_L_OFF,
  .jne .r3 (.imm NULL) 334,
  .mov64 .r0 (.imm E_KEY_DOES_NOT_EXIST),
  .exit,
  .ldx .dword .r3 .r3 TREE_NODE_CHILD_R_OFF,
  .jne .r3 (.imm NULL) 334,
  .mov64 .r0 (.imm E_KEY_DOES_NOT_EXIST),
  .exit,
  .ldx .dword .r4 .r3 TREE_NODE_CHILD_L_OFF,
  .jeq .r4 (.imm NULL) 356,
  .ldx .dword .r5 .r3 TREE_NODE_CHILD_R_OFF,
  .jeq .r5 (.imm NULL) 358,
  .ldx .dword .r4 .r5 TREE_NODE_CHILD_L_OFF,
  .jeq .r4 (.imm NULL) 353,
  .mov64 .r5 (.reg .r4),
  .ja 349,
  .ldx .word .r4 .r5 TREE_NODE_KEY_OFF,
  .stx .word .r3 TREE_NODE_KEY_OFF .r4,
  .mov64 .r3 (.reg .r5),
  .ldx .dword .r4 .r3 TREE_NODE_CHILD_R_OFF,
  .jeq .r4 (.imm NULL) 385,
  .ldx .dword .r5 .r3 TREE_NODE_PARENT_OFF,
  .stx .dword .r4 TREE_NODE_PARENT_OFF .r5,
  .st .byte .r4 TREE_NODE_COLOR_OFF TREE_COLOR_B,
  .jeq .r5 (.imm NULL) 378,
  .ldx .dword .r6 .r5 TREE_NODE_CHILD_R_OFF,
  .jne .r3 (.reg .r6) 371,
  .stx .dword .r5 TREE_NODE_CHILD_R_OFF .r4,
  .st .dword .r3 TREE_NODE_CHILD_L_OFF NULL,
  .st .dword .r3 TREE_NODE_CHILD_R_OFF NULL,
  .ldx .dword .r4 .r1 IB_TREE_DATA_TOP_OFF,
  .stx .dword .r3 TREE_NODE_PARENT_OFF .r4,
  .stx .dword .r1 IB_TREE_DATA_TOP_OFF .r3,
  .exit,
  .stx .dword .r5 TREE_NODE_CHILD_L_OFF .r4,
  .st .dword .r3 TREE_NODE_CHILD_L_OFF NULL,
  .st .dword .r3 TREE_NODE_CHILD_R_OFF NULL,
  .ldx .dword .r4 .r1 IB_TREE_DATA_TOP_OFF,
  .stx .dword .r3 TREE_NODE_PARENT_OFF .r4,
  .stx .dword .r1 IB_TREE_DATA_TOP_OFF .r3,
  .exit,
  .stx .dword .r1 IB_TREE_DATA_ROOT_OFF .r4,
  .st .dword .r3 TREE_NODE_CHILD_L_OFF NULL,
  .st .dword .r3 TREE_NODE_CHILD_R_OFF NULL,
  .ldx .dword .r4 .r1 IB_TREE_DATA_TOP_OFF,
  .stx .dword .r3 TREE_NODE_PARENT_OFF .r4,
  .stx .dword .r1 IB_TREE_DATA_TOP_OFF .r3,
  .exit,
  .ldx .dword .r5 .r3 TREE_NODE_PARENT_OFF,
  .jne .r5 (.imm NULL) 394,
  .st .dword .r1 IB_TREE_DATA_ROOT_OFF NULL,
  .st .dword .r3 TREE_NODE_CHILD_L_OFF NULL,
  .st .dword .r3 TREE_NODE_CHILD_R_OFF NULL,
  .ldx .dword .r4 .r1 IB_TREE_DATA_TOP_OFF,
  .stx .dword .r3 TREE_NODE_PARENT_OFF .r4,
  .stx .dword .r1 IB_TREE_DATA_TOP_OFF .r3,
  .exit,
  .ldx .byte .r4 .r3 TREE_NODE_COLOR_OFF,
  .jne .r4 (.imm TREE_COLOR_R) 412,
  .ldx .dword .r4 .r5 TREE_NODE_CHILD_R_OFF,
  .jne .r3 (.reg .r4) 405,
  .st .dword .r5 TREE_NODE_CHILD_R_OFF NULL,
  .st .dword .r3 TREE_NODE_CHILD_L_OFF NULL,
  .st .dword .r3 TREE_NODE_CHILD_R_OFF NULL,
  .ldx .dword .r4 .r1 IB_TREE_DATA_TOP_OFF,
  .stx .dword .r3 TREE_NODE_PARENT_OFF .r4,
  .stx .dword .r1 IB_TREE_DATA_TOP_OFF .r3,
  .exit,
  .st .dword .r5 TREE_NODE_CHILD_L_OFF NULL,
  .st .dword .r3 TREE_NODE_CHILD_L_OFF NULL,
  .st .dword .r3 TREE_NODE_CHILD_R_OFF NULL,
  .ldx .dword .r4 .r1 IB_TREE_DATA_TOP_OFF,
  .stx .dword .r3 TREE_NODE_PARENT_OFF .r4,
  .stx .dword .r1 IB_TREE_DATA_TOP_OFF .r3,
  .exit,
  .mov64 .r2 (.reg .r3),
  .ldx .dword .r5 .r3 TREE_NODE_PARENT_OFF,
  .ldx .dword .r4 .r5 TREE_NODE_CHILD_L_OFF,
  .jne .r3 (.reg .r4) 418,
  .st .dword .r5 TREE_NODE_CHILD_L_OFF NULL,
  .ja 468,
  .st .dword .r5 TREE_NODE_CHILD_R_OFF NULL,
  .ldx .dword .r6 .r5 TREE_NODE_CHILD_L_OFF,
  .ldx .dword .r7 .r6 TREE_NODE_CHILD_L_OFF,
  .ldx .dword .r8 .r6 TREE_NODE_CHILD_R_OFF,
  .ldx .byte .r9 .r6 TREE_NODE_COLOR_OFF,
  .jeq .r9 (.imm TREE_COLOR_R) 452,
  .jeq .r7 (.imm NULL) 427,
  .ldx .byte .r9 .r7 TREE_NODE_COLOR_OFF,
  .jeq .r9 (.imm TREE_COLOR_R) 447,
  .jeq .r8 (.imm NULL) 430,
  .ldx .byte .r9 .r8 TREE_NODE_COLOR_OFF,
  .jeq .r9 (.imm TREE_COLOR_R) 443,
  .jeq .r5 (.imm NULL) 468,
  .ldx .byte .r9 .r5 TREE_NODE_COLOR_OFF,
  .jne .r9 (.imm TREE_COLOR_R) 436,
  .st .byte .r6 TREE_NODE_COLOR_OFF TREE_COLOR_R,
  .st .byte .r5 TREE_NODE_COLOR_OFF TREE_COLOR_B,
  .ja 468,
  .st .byte .r6 TREE_NODE_COLOR_OFF TREE_COLOR_R,
  .mov64 .r3 (.reg .r5),
  .ldx .dword .r5 .r3 TREE_NODE_PARENT_OFF,
  .jeq .r5 (.imm NULL) 443,
  .ldx .dword .r4 .r5 TREE_NODE_CHILD_L_OFF,
  .jeq .r3 (.reg .r4) 468,
  .ja 419,
  .st .byte .r6 TREE_NODE_COLOR_OFF TREE_COLOR_R,
  .st .byte .r8 TREE_NODE_COLOR_OFF TREE_COLOR_B,
  .mov64 .r7 (.reg .r6),
  .mov64 .r6 (.reg .r8),
  .ldx .byte .r4 .r5 TREE_NODE_COLOR_OFF,
  .stx .byte .r6 TREE_NODE_COLOR_OFF .r4,
  .st .byte .r5 TREE_NODE_COLOR_OFF TREE_COLOR_B,
  .st .byte .r7 TREE_NODE_COLOR_OFF TREE_COLOR_B,
  .ja 468,
  .st .byte .r5 TREE_NODE_COLOR_OFF TREE_COLOR_R,
  .st .byte .r6 TREE_NODE_COLOR_OFF TREE_COLOR_B,
  .mov64 .r6 (.reg .r8),
  .ldx .dword .r4 .r6 TREE_NODE_CHILD_L_OFF,
  .mov64 .r7 (.reg .r4),
  .jeq .r7 (.imm NULL) 460,
  .ldx .byte .r4 .r7 TREE_NODE_COLOR_OFF,
  .jeq .r4 (.imm TREE_COLOR_R) 447,
  .ldx .dword .r4 .r6 TREE_NODE_CHILD_R_OFF,
  .mov64 .r8 (.reg .r4),
  .jeq .r8 (.imm NULL) 465,
  .ldx .byte .r4 .r8 TREE_NODE_COLOR_OFF,
  .jeq .r4 (.imm TREE_COLOR_R) 443,
  .st .byte .r6 TREE_NODE_COLOR_OFF TREE_COLOR_R,
  .st .byte .r5 TREE_NODE_COLOR_OFF TREE_COLOR_B,
  .ja 468,
  .st .dword .r2 TREE_NODE_CHILD_L_OFF NULL,
  .st .dword .r2 TREE_NODE_CHILD_R_OFF NULL,
  .ldx .dword .r4 .r1 IB_TREE_DATA_TOP_OFF,
  .stx .dword .r2 TREE_NODE_PARENT_OFF .r4,
  .stx .dword .r1 IB_TREE_DATA_TOP_OFF .r2,
  .exit,
  .mov64 .r0 (.imm E_INSTRUCTION_DATA),
  .exit,
  .mov64 .r0 (.imm E_INSTRUCTION_DATA_LEN),
  .exit,
  .mov64 .r0 (.imm E_N_ACCOUNTS),
  .exit,
  .mov64 .r0 (.imm E_N_ACCOUNTS_INSERT_ALLOCATION),
  .exit,
  .mov64 .r0 (.imm E_PDA_MISMATCH),
  .exit,
  .mov64 .r0 (.imm E_RENT_ADDRESS),
  .exit,
  .mov64 .r0 (.imm E_RENT_DUPLICATE),
  .exit,
  .mov64 .r0 (.imm E_SYSTEM_PROGRAM_DATA_LEN),
  .exit,
  .mov64 .r0 (.imm E_SYSTEM_PROGRAM_DUPLICATE),
  .exit,
  .mov64 .r0 (.imm E_TREE_DATA_LEN),
  .exit,
  .mov64 .r0 (.imm E_TREE_DUPLICATE),
  .exit,
  .mov64 .r0 (.imm E_USER_DATA_LEN),
  .exit
]

end TreeProg
