-- Auto-generated by qedgen asm2lean from counter.s
-- DO NOT EDIT — regenerate with: qedgen asm2lean --input counter.s

import QEDGen.Solana.SBPF

namespace CounterProg

open QEDGen.Solana.SBPF

/-! ## .equ constants -/

abbrev E_N_ACCOUNTS : Nat := 1
abbrev E_USER_DATA_LEN : Nat := 2
abbrev E_PDA_DATA_LEN : Nat := 3
abbrev E_SYSTEM_PROGRAM_DATA_LEN : Nat := 4
abbrev E_PDA_DUPLICATE : Nat := 5
abbrev E_SYSTEM_PROGRAM_DUPLICATE : Nat := 6
abbrev E_UNABLE_TO_DERIVE_PDA : Nat := 7
abbrev E_PDA_MISMATCH : Nat := 8
abbrev E_INVALID_INSTRUCTION_DATA_LEN : Nat := 9
abbrev SIZE_OF_PUBKEY : Nat := 32
abbrev SIZE_OF_U8 : Nat := 1
abbrev SIZE_OF_U64 : Int := 8
abbrev SIZE_OF_U64_2X : Int := 16
abbrev SIZE_OF_U64_3X : Int := 24
abbrev NON_DUP_MARKER : Nat := 0xff
abbrev DATA_LEN_ZERO : Nat := 0
abbrev DATA_LEN_SYSTEM_PROGRAM : Nat := 14
abbrev N_ACCOUNTS_INCREMENT : Nat := 2
abbrev N_ACCOUNTS_INIT : Nat := 3
abbrev N_ACCOUNTS_OFF : Int := 0
abbrev USER_DATA_LEN_OFF : Int := 88
abbrev USER_PUBKEY_OFF : Nat := 16
abbrev USER_DATA_TO_PDA_OWNER_OFF : Nat := 10288
abbrev PDA_NON_DUP_MARKER_OFF : Int := 10344
abbrev PDA_PUBKEY_OFF : Nat := 10352
abbrev PDA_DATA_LEN_OFF : Int := 10424
abbrev PDA_DATA_WITH_ACCOUNT_OVERHEAD : Nat := 137
abbrev PDA_COUNTER_OFF : Int := 10432
abbrev PDA_BUMP_SEED_OFF : Int := 10440
abbrev SYSTEM_PROGRAM_NON_DUP_MARKER_OFF : Int := 20680
abbrev SYSTEM_PROGRAM_DATA_LEN_OFF : Int := 20760
abbrev PROGRAM_ID_INIT_OFF : Nat := 31040
abbrev INSTRUCTION_DATA_LEN_INC_OFF : Int := 20696
abbrev COUNTER_INCREMENT_OFF : Int := 20704
abbrev PROGRAM_ID_INC_OFF : Nat := 20712
abbrev INIT_CPI_N_ACCOUNTS : Nat := 2
abbrev INIT_CPI_INSN_DATA_LEN : Nat := 52
abbrev INIT_CPI_DISCRIMINATOR : Nat := 0
abbrev INIT_CPI_N_SIGNERS_SEEDS : Nat := 1
abbrev INIT_CPI_ACCT_SIZE : Nat := 9
abbrev STK_INC_SEED_0_ADDR_OFF : Int := 64
abbrev STK_INC_SEED_0_LEN_OFF : Int := 56
abbrev STK_INC_SEED_1_ADDR_OFF : Int := 48
abbrev STK_INC_SEED_1_LEN_OFF : Int := 40
abbrev STK_INC_PDA_OFF : Nat := 32
abbrev STK_INIT_SYSTEM_PROGRAM_PUBKEY_OFF : Nat := 384
abbrev STK_INIT_INSN_OFF : Int := 352
abbrev STK_INIT_INSN_ACCOUNTS_ADDR_OFF : Int := 344
abbrev STK_INIT_INSN_ACCOUNTS_LEN_OFF : Int := 336
abbrev STK_INIT_INSN_DATA_ADDR_OFF : Int := 328
abbrev STK_INIT_INSN_DATA_LEN_OFF : Int := 320
abbrev STK_INIT_SYSTEM_PROGRAM_PUBKEY_TO_ACCOUNT_METAS_OFF : Nat := 72
abbrev STK_INIT_ACCOUNT_METAS_TO_INSN_DATA_OFF : Nat := 32
abbrev STK_INIT_INSN_DATA_OFF : Nat := 280
abbrev STK_INIT_INSN_DATA_LAMPORTS_OFF : Int := 276
abbrev STK_INIT_INSN_DATA_SPACE_OFF : Int := 268
abbrev STK_INIT_INSN_DATA_OWNER_OFF : Nat := 260
abbrev STK_INIT_ACCT_INFOS_OFF : Nat := 224
abbrev STK_INIT_ACCT_META_USER_PUBKEY_ADDR_OFF : Int := 312
abbrev STK_INIT_ACCT_META_USER_IS_WRITABLE_OFF : Int := 304
abbrev STK_INIT_ACCT_META_USER_IS_SIGNER_OFF : Nat := 303
abbrev STK_INIT_ACCT_META_PDA_PUBKEY_ADDR_OFF : Int := 296
abbrev STK_INIT_ACCT_META_PDA_IS_WRITABLE_OFF : Int := 288
abbrev STK_INIT_ACCT_META_PDA_IS_SIGNER_OFF : Nat := 287
abbrev STK_INIT_ACCT_INFO_USER_KEY_ADDR_OFF : Int := 224
abbrev STK_INIT_ACCT_INFO_PDA_KEY_ADDR_OFF : Int := 168
abbrev STK_INIT_ACCT_INFO_USER_LAMPORTS_ADDR_OFF : Int := 216
abbrev STK_INIT_ACCT_INFO_PDA_LAMPORTS_ADDR_OFF : Int := 160
abbrev STK_INIT_ACCT_INFO_USER_OWNER_ADDR_OFF : Int := 192
abbrev STK_INIT_ACCT_INFO_PDA_OWNER_ADDR_OFF : Int := 136
abbrev STK_INIT_ACCT_INFO_USER_DATA_ADDR_OFF : Int := 200
abbrev STK_INIT_ACCT_INFO_PDA_DATA_ADDR_OFF : Int := 144
abbrev STK_INIT_ACCT_INFO_USER_IS_SIGNER_OFF : Int := 176
abbrev STK_INIT_ACCT_INFO_USER_IS_WRITABLE_OFF : Nat := 175
abbrev STK_INIT_ACCT_INFO_PDA_IS_SIGNER_OFF : Int := 120
abbrev STK_INIT_ACCT_INFO_PDA_IS_WRITABLE_OFF : Nat := 119
abbrev STK_INIT_SEED_0_ADDR_OFF : Int := 112
abbrev STK_INIT_SEED_0_LEN_OFF : Int := 104
abbrev STK_INIT_SEED_1_ADDR_OFF : Int := 96
abbrev STK_INIT_SEED_1_LEN_OFF : Int := 88
abbrev STK_INIT_SIGNERS_SEEDS_OFF : Int := 80
abbrev STK_INIT_SIGNER_SEEDS_0_LEN_OFF : Int := 72
abbrev STK_INIT_PDA_OFF : Nat := 64
abbrev STK_INIT_RENT_OFF : Nat := 32
abbrev STK_INIT_BUMP_SEED_OFF : Int := 8
abbrev NO_OFFSET : Int := 0
abbrev SUCCESS : Nat := 0
abbrev BOOL_TRUE : Nat := 1
abbrev BOOL_TRUE_2X : Nat := 0x101
abbrev N_SIGNER_SEEDS : Nat := 2
abbrev COMPARE_EQUAL : Nat := 0

/-! ## Program (chunked lookup for O(1) simp) -/

private def progAt_0 : Nat → Option QEDGen.Solana.SBPF.Insn
  | 0 => some (.ldx .dword .r2 .r1 N_ACCOUNTS_OFF)  -- 0: entrypoint
  | 1 => some (.jeq .r2 (.imm N_ACCOUNTS_INCREMENT) 116)  -- 1
  | 2 => some (.jeq .r2 (.imm N_ACCOUNTS_INIT) 5)  -- 2
  | 3 => some (.mov64 .r0 (.imm E_N_ACCOUNTS))  -- 3
  | 4 => some (.exit)  -- 4
  | 5 => some (.ldx .dword .r2 .r1 USER_DATA_LEN_OFF)  -- 5: initialize
  | 6 => some (.jne .r2 (.imm DATA_LEN_ZERO) 162)  -- 6
  | 7 => some (.ldx .byte .r2 .r1 PDA_NON_DUP_MARKER_OFF)  -- 7
  | 8 => some (.jne .r2 (.imm NON_DUP_MARKER) 168)  -- 8
  | 9 => some (.ldx .dword .r2 .r1 PDA_DATA_LEN_OFF)  -- 9
  | 10 => some (.jne .r2 (.imm DATA_LEN_ZERO) 164)  -- 10
  | 11 => some (.ldx .byte .r2 .r1 SYSTEM_PROGRAM_NON_DUP_MARKER_OFF)  -- 11
  | 12 => some (.jne .r2 (.imm NON_DUP_MARKER) 170)  -- 12
  | 13 => some (.ldx .dword .r2 .r1 SYSTEM_PROGRAM_DATA_LEN_OFF)  -- 13
  | 14 => some (.jne .r2 (.imm DATA_LEN_SYSTEM_PROGRAM) 166)  -- 14
  | 15 => some (.mov64 .r2 (.reg .r1))  -- 15
  | 16 => some (.add64 .r2 (.imm USER_PUBKEY_OFF))  -- 16
  | 17 => some (.stx .dword .r10 (-STK_INIT_SEED_0_ADDR_OFF) .r2)  -- 17
  | 18 => some (.st .dword .r10 (-STK_INIT_SEED_0_LEN_OFF) SIZE_OF_PUBKEY)  -- 18
  | 19 => some (.mov64 .r2 (.reg .r10))  -- 19
  | 20 => some (.sub64 .r2 (.imm STK_INIT_BUMP_SEED_OFF))  -- 20
  | 21 => some (.stx .dword .r10 (-STK_INIT_SEED_1_ADDR_OFF) .r2)  -- 21
  | 22 => some (.st .dword .r10 (-STK_INIT_SEED_1_LEN_OFF) SIZE_OF_U8)  -- 22
  | 23 => some (.mov64 .r9 (.reg .r1))  -- 23
  | 24 => some (.mov64 .r1 (.reg .r10))  -- 24
  | 25 => some (.sub64 .r1 (.imm STK_INIT_SEED_0_ADDR_OFF))  -- 25
  | 26 => some (.mov64 .r2 (.imm 1))  -- 26
  | 27 => some (.mov64 .r3 (.reg .r9))  -- 27
  | 28 => some (.add64 .r3 (.imm PROGRAM_ID_INIT_OFF))  -- 28
  | 29 => some (.mov64 .r4 (.reg .r10))  -- 29
  | 30 => some (.sub64 .r4 (.imm STK_INIT_PDA_OFF))  -- 30
  | 31 => some (.mov64 .r5 (.reg .r10))  -- 31
  | 32 => some (.sub64 .r5 (.imm STK_INIT_BUMP_SEED_OFF))  -- 32
  | 33 => some (.call .sol_try_find_program_address)  -- 33
  | 34 => some (.mov64 .r1 (.reg .r9))  -- 34
  | 35 => some (.add64 .r1 (.imm PDA_PUBKEY_OFF))  -- 35
  | 36 => some (.stx .dword .r10 (-STK_INIT_ACCT_META_PDA_PUBKEY_ADDR_OFF) .r1)  -- 36
  | 37 => some (.stx .dword .r10 (-STK_INIT_ACCT_INFO_PDA_KEY_ADDR_OFF) .r1)  -- 37
  | 38 => some (.mov64 .r2 (.reg .r10))  -- 38
  | 39 => some (.sub64 .r2 (.imm STK_INIT_PDA_OFF))  -- 39
  | 40 => some (.ldx .dword .r3 .r1 0)  -- 40
  | 41 => some (.ldx .dword .r4 .r2 0)  -- 41
  | 42 => some (.jne .r3 (.reg .r4) 172)  -- 42
  | 43 => some (.ldx .dword .r3 .r1 SIZE_OF_U64)  -- 43
  | 44 => some (.ldx .dword .r4 .r2 SIZE_OF_U64)  -- 44
  | 45 => some (.jne .r3 (.reg .r4) 172)  -- 45
  | 46 => some (.ldx .dword .r3 .r1 SIZE_OF_U64_2X)  -- 46
  | 47 => some (.ldx .dword .r4 .r2 SIZE_OF_U64_2X)  -- 47
  | 48 => some (.jne .r3 (.reg .r4) 172)  -- 48
  | 49 => some (.ldx .dword .r3 .r1 SIZE_OF_U64_3X)  -- 49
  | 50 => some (.ldx .dword .r4 .r2 SIZE_OF_U64_3X)  -- 50
  | 51 => some (.jne .r3 (.reg .r4) 172)  -- 51
  | 52 => some (.mov64 .r1 (.reg .r10))  -- 52
  | 53 => some (.sub64 .r1 (.imm STK_INIT_RENT_OFF))  -- 53
  | 54 => some (.call .sol_get_rent_sysvar)  -- 54
  | 55 => some (.ldx .dword .r2 .r1 NO_OFFSET)  -- 55
  | 56 => some (.mul64 .r2 (.imm PDA_DATA_WITH_ACCOUNT_OVERHEAD))  -- 56
  | 57 => some (.stx .dword .r10 (-STK_INIT_INSN_DATA_LAMPORTS_OFF) .r2)  -- 57
  | 58 => some (.mov64 .r3 (.reg .r10))  -- 58
  | 59 => some (.sub64 .r3 (.imm STK_INIT_SYSTEM_PROGRAM_PUBKEY_OFF))  -- 59
  | 60 => some (.stx .dword .r10 (-STK_INIT_INSN_OFF) .r3)  -- 60
  | 61 => some (.add64 .r3 (.imm STK_INIT_SYSTEM_PROGRAM_PUBKEY_TO_ACCOUNT_METAS_OFF))  -- 61
  | 62 => some (.stx .dword .r10 (-STK_INIT_INSN_ACCOUNTS_ADDR_OFF) .r3)  -- 62
  | 63 => some (.st .dword .r10 (-STK_INIT_INSN_ACCOUNTS_LEN_OFF) INIT_CPI_N_ACCOUNTS)  -- 63
  | 64 => some (.add64 .r3 (.imm STK_INIT_ACCOUNT_METAS_TO_INSN_DATA_OFF))  -- 64
  | 65 => some (.stx .dword .r10 (-STK_INIT_INSN_DATA_ADDR_OFF) .r3)  -- 65
  | 66 => some (.st .dword .r10 (-STK_INIT_INSN_DATA_LEN_OFF) INIT_CPI_INSN_DATA_LEN)  -- 66
  | 67 => some (.st .dword .r10 (-STK_INIT_INSN_DATA_SPACE_OFF) INIT_CPI_ACCT_SIZE)  -- 67
  | 68 => some (.mov64 .r1 (.reg .r10))  -- 68
  | 69 => some (.sub64 .r1 (.imm STK_INIT_INSN_DATA_OWNER_OFF))  -- 69
  | 70 => some (.mov64 .r2 (.reg .r9))  -- 70
  | 71 => some (.add64 .r2 (.imm PROGRAM_ID_INIT_OFF))  -- 71
  | 72 => some (.ldx .dword .r3 .r2 0)  -- 72
  | 73 => some (.stx .dword .r1 0 .r3)  -- 73
  | 74 => some (.ldx .dword .r3 .r2 SIZE_OF_U64)  -- 74
  | 75 => some (.stx .dword .r1 SIZE_OF_U64 .r3)  -- 75
  | 76 => some (.ldx .dword .r3 .r2 SIZE_OF_U64_2X)  -- 76
  | 77 => some (.stx .dword .r1 SIZE_OF_U64_2X .r3)  -- 77
  | 78 => some (.ldx .dword .r3 .r2 SIZE_OF_U64_3X)  -- 78
  | 79 => some (.stx .dword .r1 SIZE_OF_U64_3X .r3)  -- 79
  | 80 => some (.st .half .r10 (-STK_INIT_ACCT_META_USER_IS_WRITABLE_OFF) BOOL_TRUE_2X)  -- 80
  | 81 => some (.st .half .r10 (-STK_INIT_ACCT_META_PDA_IS_WRITABLE_OFF) BOOL_TRUE_2X)  -- 81
  | 82 => some (.st .half .r10 (-STK_INIT_ACCT_INFO_USER_IS_SIGNER_OFF) BOOL_TRUE_2X)  -- 82
  | 83 => some (.st .half .r10 (-STK_INIT_ACCT_INFO_PDA_IS_SIGNER_OFF) BOOL_TRUE_2X)  -- 83
  | 84 => some (.mov64 .r2 (.reg .r9))  -- 84
  | 85 => some (.add64 .r2 (.imm USER_PUBKEY_OFF))  -- 85
  | 86 => some (.stx .dword .r10 (-STK_INIT_ACCT_META_USER_PUBKEY_ADDR_OFF) .r2)  -- 86
  | 87 => some (.stx .dword .r10 (-STK_INIT_ACCT_INFO_USER_KEY_ADDR_OFF) .r2)  -- 87
  | 88 => some (.add64 .r2 (.imm SIZE_OF_PUBKEY))  -- 88
  | 89 => some (.stx .dword .r10 (-STK_INIT_ACCT_INFO_USER_OWNER_ADDR_OFF) .r2)  -- 89
  | 90 => some (.add64 .r2 (.imm SIZE_OF_PUBKEY))  -- 90
  | 91 => some (.stx .dword .r10 (-STK_INIT_ACCT_INFO_USER_LAMPORTS_ADDR_OFF) .r2)  -- 91
  | 92 => some (.add64 .r2 (.imm SIZE_OF_U64_2X))  -- 92
  | 93 => some (.stx .dword .r10 (-STK_INIT_ACCT_INFO_USER_DATA_ADDR_OFF) .r2)  -- 93
  | 94 => some (.add64 .r2 (.imm USER_DATA_TO_PDA_OWNER_OFF))  -- 94
  | 95 => some (.stx .dword .r10 (-STK_INIT_ACCT_INFO_PDA_OWNER_ADDR_OFF) .r2)  -- 95
  | 96 => some (.add64 .r2 (.imm SIZE_OF_PUBKEY))  -- 96
  | 97 => some (.stx .dword .r10 (-STK_INIT_ACCT_INFO_PDA_LAMPORTS_ADDR_OFF) .r2)  -- 97
  | 98 => some (.add64 .r2 (.imm SIZE_OF_U64_2X))  -- 98
  | 99 => some (.stx .dword .r10 (-STK_INIT_ACCT_INFO_PDA_DATA_ADDR_OFF) .r2)  -- 99
  | _ => none

private def progAt_1 : Nat → Option QEDGen.Solana.SBPF.Insn
  | 100 => some (.mov64 .r2 (.reg .r10))  -- 100
  | 101 => some (.sub64 .r2 (.imm STK_INIT_SEED_0_ADDR_OFF))  -- 101
  | 102 => some (.stx .dword .r10 (-STK_INIT_SIGNERS_SEEDS_OFF) .r2)  -- 102
  | 103 => some (.st .dword .r10 (-STK_INIT_SIGNER_SEEDS_0_LEN_OFF) N_SIGNER_SEEDS)  -- 103
  | 104 => some (.mov64 .r1 (.reg .r10))  -- 104
  | 105 => some (.sub64 .r1 (.imm STK_INIT_INSN_OFF))  -- 105
  | 106 => some (.mov64 .r2 (.reg .r10))  -- 106
  | 107 => some (.sub64 .r2 (.imm STK_INIT_ACCT_INFOS_OFF))  -- 107
  | 108 => some (.mov64 .r3 (.imm INIT_CPI_N_ACCOUNTS))  -- 108
  | 109 => some (.mov64 .r4 (.reg .r10))  -- 109
  | 110 => some (.sub64 .r4 (.imm STK_INIT_SIGNERS_SEEDS_OFF))  -- 110
  | 111 => some (.mov64 .r5 (.imm INIT_CPI_N_SIGNERS_SEEDS))  -- 111
  | 112 => some (.call .sol_invoke_signed_c)  -- 112
  | 113 => some (.ldx .byte .r2 .r10 (-STK_INIT_BUMP_SEED_OFF))  -- 113
  | 114 => some (.stx .byte .r9 PDA_BUMP_SEED_OFF .r2)  -- 114
  | 115 => some (.exit)  -- 115
  | 116 => some (.ldx .dword .r9 .r1 USER_DATA_LEN_OFF)  -- 116: increment
  | 117 => some (.add64 .r9 (.imm 7))  -- 117
  | 118 => some (.and64 .r9 (.imm (-8)))  -- 118
  | 119 => some (.add64 .r9 (.reg .r1))  -- 119
  | 120 => some (.ldx .byte .r8 .r9 PDA_NON_DUP_MARKER_OFF)  -- 120
  | 121 => some (.jne .r8 (.imm NON_DUP_MARKER) 168)  -- 121
  | 122 => some (.ldx .dword .r8 .r9 PDA_DATA_LEN_OFF)  -- 122
  | 123 => some (.jne .r8 (.imm INIT_CPI_ACCT_SIZE) 164)  -- 123
  | 124 => some (.ldx .dword .r8 .r9 INSTRUCTION_DATA_LEN_INC_OFF)  -- 124
  | 125 => some (.jne .r8 (.imm SIZE_OF_U64) 174)  -- 125
  | 126 => some (.mov64 .r3 (.reg .r9))  -- 126
  | 127 => some (.add64 .r3 (.imm PROGRAM_ID_INC_OFF))  -- 127
  | 128 => some (.mov64 .r6 (.reg .r9))  -- 128
  | 129 => some (.add64 .r6 (.imm PDA_PUBKEY_OFF))  -- 129
  | 130 => some (.ldx .dword .r8 .r9 COUNTER_INCREMENT_OFF)  -- 130
  | 131 => some (.ldx .dword .r7 .r9 PDA_COUNTER_OFF)  -- 131
  | 132 => some (.add64 .r7 (.reg .r8))  -- 132
  | 133 => some (.stx .dword .r9 PDA_COUNTER_OFF .r7)  -- 133
  | 134 => some (.add64 .r1 (.imm USER_PUBKEY_OFF))  -- 134
  | 135 => some (.stx .dword .r10 (-STK_INC_SEED_0_ADDR_OFF) .r1)  -- 135
  | 136 => some (.st .dword .r10 (-STK_INC_SEED_0_LEN_OFF) SIZE_OF_PUBKEY)  -- 136
  | 137 => some (.add64 .r9 (.imm PDA_BUMP_SEED_OFF))  -- 137
  | 138 => some (.stx .dword .r10 (-STK_INC_SEED_1_ADDR_OFF) .r9)  -- 138
  | 139 => some (.st .dword .r10 (-STK_INC_SEED_1_LEN_OFF) SIZE_OF_U8)  -- 139
  | 140 => some (.mov64 .r1 (.reg .r10))  -- 140
  | 141 => some (.sub64 .r1 (.imm STK_INC_SEED_0_ADDR_OFF))  -- 141
  | 142 => some (.mov64 .r2 (.imm N_SIGNER_SEEDS))  -- 142
  | 143 => some (.mov64 .r4 (.reg .r10))  -- 143
  | 144 => some (.sub64 .r4 (.imm STK_INC_PDA_OFF))  -- 144
  | 145 => some (.call .sol_create_program_address)  -- 145
  | 146 => some (.jne .r0 (.imm SUCCESS) 176)  -- 146
  | 147 => some (.mov64 .r1 (.reg .r6))  -- 147
  | 148 => some (.mov64 .r2 (.reg .r4))  -- 148
  | 149 => some (.ldx .dword .r3 .r1 0)  -- 149
  | 150 => some (.ldx .dword .r4 .r2 0)  -- 150
  | 151 => some (.jne .r3 (.reg .r4) 172)  -- 151
  | 152 => some (.ldx .dword .r3 .r1 SIZE_OF_U64)  -- 152
  | 153 => some (.ldx .dword .r4 .r2 SIZE_OF_U64)  -- 153
  | 154 => some (.jne .r3 (.reg .r4) 172)  -- 154
  | 155 => some (.ldx .dword .r3 .r1 SIZE_OF_U64_2X)  -- 155
  | 156 => some (.ldx .dword .r4 .r2 SIZE_OF_U64_2X)  -- 156
  | 157 => some (.jne .r3 (.reg .r4) 172)  -- 157
  | 158 => some (.ldx .dword .r3 .r1 SIZE_OF_U64_3X)  -- 158
  | 159 => some (.ldx .dword .r4 .r2 SIZE_OF_U64_3X)  -- 159
  | 160 => some (.jne .r3 (.reg .r4) 172)  -- 160
  | 161 => some (.exit)  -- 161
  | 162 => some (.mov32 .r0 (.imm E_USER_DATA_LEN))  -- 162: e_user_data_len
  | 163 => some (.exit)  -- 163
  | 164 => some (.mov32 .r0 (.imm E_PDA_DATA_LEN))  -- 164: e_pda_data_len
  | 165 => some (.exit)  -- 165
  | 166 => some (.mov32 .r0 (.imm E_SYSTEM_PROGRAM_DATA_LEN))  -- 166: e_system_program_data_len
  | 167 => some (.exit)  -- 167
  | 168 => some (.mov32 .r0 (.imm E_PDA_DUPLICATE))  -- 168: e_pda_duplicate
  | 169 => some (.exit)  -- 169
  | 170 => some (.mov32 .r0 (.imm E_SYSTEM_PROGRAM_DUPLICATE))  -- 170: e_system_program_duplicate
  | 171 => some (.exit)  -- 171
  | 172 => some (.mov32 .r0 (.imm E_PDA_MISMATCH))  -- 172: e_pda_mismatch
  | 173 => some (.exit)  -- 173
  | 174 => some (.mov32 .r0 (.imm E_INVALID_INSTRUCTION_DATA_LEN))  -- 174: e_invalid_instruction_data_len
  | 175 => some (.exit)  -- 175
  | 176 => some (.mov32 .r0 (.imm E_UNABLE_TO_DERIVE_PDA))  -- 176: e_unable_to_derive_pda
  | 177 => some (.exit)  -- 177
  | _ => none

def progAt (n : Nat) : Option QEDGen.Solana.SBPF.Insn :=
  if n < 100 then progAt_0 n
  else
  progAt_1 n

def prog : Program := #[
  .ldx .dword .r2 .r1 N_ACCOUNTS_OFF,
  .jeq .r2 (.imm N_ACCOUNTS_INCREMENT) 116,
  .jeq .r2 (.imm N_ACCOUNTS_INIT) 5,
  .mov64 .r0 (.imm E_N_ACCOUNTS),
  .exit,
  .ldx .dword .r2 .r1 USER_DATA_LEN_OFF,
  .jne .r2 (.imm DATA_LEN_ZERO) 162,
  .ldx .byte .r2 .r1 PDA_NON_DUP_MARKER_OFF,
  .jne .r2 (.imm NON_DUP_MARKER) 168,
  .ldx .dword .r2 .r1 PDA_DATA_LEN_OFF,
  .jne .r2 (.imm DATA_LEN_ZERO) 164,
  .ldx .byte .r2 .r1 SYSTEM_PROGRAM_NON_DUP_MARKER_OFF,
  .jne .r2 (.imm NON_DUP_MARKER) 170,
  .ldx .dword .r2 .r1 SYSTEM_PROGRAM_DATA_LEN_OFF,
  .jne .r2 (.imm DATA_LEN_SYSTEM_PROGRAM) 166,
  .mov64 .r2 (.reg .r1),
  .add64 .r2 (.imm USER_PUBKEY_OFF),
  .stx .dword .r10 (-STK_INIT_SEED_0_ADDR_OFF) .r2,
  .st .dword .r10 (-STK_INIT_SEED_0_LEN_OFF) SIZE_OF_PUBKEY,
  .mov64 .r2 (.reg .r10),
  .sub64 .r2 (.imm STK_INIT_BUMP_SEED_OFF),
  .stx .dword .r10 (-STK_INIT_SEED_1_ADDR_OFF) .r2,
  .st .dword .r10 (-STK_INIT_SEED_1_LEN_OFF) SIZE_OF_U8,
  .mov64 .r9 (.reg .r1),
  .mov64 .r1 (.reg .r10),
  .sub64 .r1 (.imm STK_INIT_SEED_0_ADDR_OFF),
  .mov64 .r2 (.imm 1),
  .mov64 .r3 (.reg .r9),
  .add64 .r3 (.imm PROGRAM_ID_INIT_OFF),
  .mov64 .r4 (.reg .r10),
  .sub64 .r4 (.imm STK_INIT_PDA_OFF),
  .mov64 .r5 (.reg .r10),
  .sub64 .r5 (.imm STK_INIT_BUMP_SEED_OFF),
  .call .sol_try_find_program_address,
  .mov64 .r1 (.reg .r9),
  .add64 .r1 (.imm PDA_PUBKEY_OFF),
  .stx .dword .r10 (-STK_INIT_ACCT_META_PDA_PUBKEY_ADDR_OFF) .r1,
  .stx .dword .r10 (-STK_INIT_ACCT_INFO_PDA_KEY_ADDR_OFF) .r1,
  .mov64 .r2 (.reg .r10),
  .sub64 .r2 (.imm STK_INIT_PDA_OFF),
  .ldx .dword .r3 .r1 0,
  .ldx .dword .r4 .r2 0,
  .jne .r3 (.reg .r4) 172,
  .ldx .dword .r3 .r1 SIZE_OF_U64,
  .ldx .dword .r4 .r2 SIZE_OF_U64,
  .jne .r3 (.reg .r4) 172,
  .ldx .dword .r3 .r1 SIZE_OF_U64_2X,
  .ldx .dword .r4 .r2 SIZE_OF_U64_2X,
  .jne .r3 (.reg .r4) 172,
  .ldx .dword .r3 .r1 SIZE_OF_U64_3X,
  .ldx .dword .r4 .r2 SIZE_OF_U64_3X,
  .jne .r3 (.reg .r4) 172,
  .mov64 .r1 (.reg .r10),
  .sub64 .r1 (.imm STK_INIT_RENT_OFF),
  .call .sol_get_rent_sysvar,
  .ldx .dword .r2 .r1 NO_OFFSET,
  .mul64 .r2 (.imm PDA_DATA_WITH_ACCOUNT_OVERHEAD),
  .stx .dword .r10 (-STK_INIT_INSN_DATA_LAMPORTS_OFF) .r2,
  .mov64 .r3 (.reg .r10),
  .sub64 .r3 (.imm STK_INIT_SYSTEM_PROGRAM_PUBKEY_OFF),
  .stx .dword .r10 (-STK_INIT_INSN_OFF) .r3,
  .add64 .r3 (.imm STK_INIT_SYSTEM_PROGRAM_PUBKEY_TO_ACCOUNT_METAS_OFF),
  .stx .dword .r10 (-STK_INIT_INSN_ACCOUNTS_ADDR_OFF) .r3,
  .st .dword .r10 (-STK_INIT_INSN_ACCOUNTS_LEN_OFF) INIT_CPI_N_ACCOUNTS,
  .add64 .r3 (.imm STK_INIT_ACCOUNT_METAS_TO_INSN_DATA_OFF),
  .stx .dword .r10 (-STK_INIT_INSN_DATA_ADDR_OFF) .r3,
  .st .dword .r10 (-STK_INIT_INSN_DATA_LEN_OFF) INIT_CPI_INSN_DATA_LEN,
  .st .dword .r10 (-STK_INIT_INSN_DATA_SPACE_OFF) INIT_CPI_ACCT_SIZE,
  .mov64 .r1 (.reg .r10),
  .sub64 .r1 (.imm STK_INIT_INSN_DATA_OWNER_OFF),
  .mov64 .r2 (.reg .r9),
  .add64 .r2 (.imm PROGRAM_ID_INIT_OFF),
  .ldx .dword .r3 .r2 0,
  .stx .dword .r1 0 .r3,
  .ldx .dword .r3 .r2 SIZE_OF_U64,
  .stx .dword .r1 SIZE_OF_U64 .r3,
  .ldx .dword .r3 .r2 SIZE_OF_U64_2X,
  .stx .dword .r1 SIZE_OF_U64_2X .r3,
  .ldx .dword .r3 .r2 SIZE_OF_U64_3X,
  .stx .dword .r1 SIZE_OF_U64_3X .r3,
  .st .half .r10 (-STK_INIT_ACCT_META_USER_IS_WRITABLE_OFF) BOOL_TRUE_2X,
  .st .half .r10 (-STK_INIT_ACCT_META_PDA_IS_WRITABLE_OFF) BOOL_TRUE_2X,
  .st .half .r10 (-STK_INIT_ACCT_INFO_USER_IS_SIGNER_OFF) BOOL_TRUE_2X,
  .st .half .r10 (-STK_INIT_ACCT_INFO_PDA_IS_SIGNER_OFF) BOOL_TRUE_2X,
  .mov64 .r2 (.reg .r9),
  .add64 .r2 (.imm USER_PUBKEY_OFF),
  .stx .dword .r10 (-STK_INIT_ACCT_META_USER_PUBKEY_ADDR_OFF) .r2,
  .stx .dword .r10 (-STK_INIT_ACCT_INFO_USER_KEY_ADDR_OFF) .r2,
  .add64 .r2 (.imm SIZE_OF_PUBKEY),
  .stx .dword .r10 (-STK_INIT_ACCT_INFO_USER_OWNER_ADDR_OFF) .r2,
  .add64 .r2 (.imm SIZE_OF_PUBKEY),
  .stx .dword .r10 (-STK_INIT_ACCT_INFO_USER_LAMPORTS_ADDR_OFF) .r2,
  .add64 .r2 (.imm SIZE_OF_U64_2X),
  .stx .dword .r10 (-STK_INIT_ACCT_INFO_USER_DATA_ADDR_OFF) .r2,
  .add64 .r2 (.imm USER_DATA_TO_PDA_OWNER_OFF),
  .stx .dword .r10 (-STK_INIT_ACCT_INFO_PDA_OWNER_ADDR_OFF) .r2,
  .add64 .r2 (.imm SIZE_OF_PUBKEY),
  .stx .dword .r10 (-STK_INIT_ACCT_INFO_PDA_LAMPORTS_ADDR_OFF) .r2,
  .add64 .r2 (.imm SIZE_OF_U64_2X),
  .stx .dword .r10 (-STK_INIT_ACCT_INFO_PDA_DATA_ADDR_OFF) .r2,
  .mov64 .r2 (.reg .r10),
  .sub64 .r2 (.imm STK_INIT_SEED_0_ADDR_OFF),
  .stx .dword .r10 (-STK_INIT_SIGNERS_SEEDS_OFF) .r2,
  .st .dword .r10 (-STK_INIT_SIGNER_SEEDS_0_LEN_OFF) N_SIGNER_SEEDS,
  .mov64 .r1 (.reg .r10),
  .sub64 .r1 (.imm STK_INIT_INSN_OFF),
  .mov64 .r2 (.reg .r10),
  .sub64 .r2 (.imm STK_INIT_ACCT_INFOS_OFF),
  .mov64 .r3 (.imm INIT_CPI_N_ACCOUNTS),
  .mov64 .r4 (.reg .r10),
  .sub64 .r4 (.imm STK_INIT_SIGNERS_SEEDS_OFF),
  .mov64 .r5 (.imm INIT_CPI_N_SIGNERS_SEEDS),
  .call .sol_invoke_signed_c,
  .ldx .byte .r2 .r10 (-STK_INIT_BUMP_SEED_OFF),
  .stx .byte .r9 PDA_BUMP_SEED_OFF .r2,
  .exit,
  .ldx .dword .r9 .r1 USER_DATA_LEN_OFF,
  .add64 .r9 (.imm 7),
  .and64 .r9 (.imm (-8)),
  .add64 .r9 (.reg .r1),
  .ldx .byte .r8 .r9 PDA_NON_DUP_MARKER_OFF,
  .jne .r8 (.imm NON_DUP_MARKER) 168,
  .ldx .dword .r8 .r9 PDA_DATA_LEN_OFF,
  .jne .r8 (.imm INIT_CPI_ACCT_SIZE) 164,
  .ldx .dword .r8 .r9 INSTRUCTION_DATA_LEN_INC_OFF,
  .jne .r8 (.imm SIZE_OF_U64) 174,
  .mov64 .r3 (.reg .r9),
  .add64 .r3 (.imm PROGRAM_ID_INC_OFF),
  .mov64 .r6 (.reg .r9),
  .add64 .r6 (.imm PDA_PUBKEY_OFF),
  .ldx .dword .r8 .r9 COUNTER_INCREMENT_OFF,
  .ldx .dword .r7 .r9 PDA_COUNTER_OFF,
  .add64 .r7 (.reg .r8),
  .stx .dword .r9 PDA_COUNTER_OFF .r7,
  .add64 .r1 (.imm USER_PUBKEY_OFF),
  .stx .dword .r10 (-STK_INC_SEED_0_ADDR_OFF) .r1,
  .st .dword .r10 (-STK_INC_SEED_0_LEN_OFF) SIZE_OF_PUBKEY,
  .add64 .r9 (.imm PDA_BUMP_SEED_OFF),
  .stx .dword .r10 (-STK_INC_SEED_1_ADDR_OFF) .r9,
  .st .dword .r10 (-STK_INC_SEED_1_LEN_OFF) SIZE_OF_U8,
  .mov64 .r1 (.reg .r10),
  .sub64 .r1 (.imm STK_INC_SEED_0_ADDR_OFF),
  .mov64 .r2 (.imm N_SIGNER_SEEDS),
  .mov64 .r4 (.reg .r10),
  .sub64 .r4 (.imm STK_INC_PDA_OFF),
  .call .sol_create_program_address,
  .jne .r0 (.imm SUCCESS) 176,
  .mov64 .r1 (.reg .r6),
  .mov64 .r2 (.reg .r4),
  .ldx .dword .r3 .r1 0,
  .ldx .dword .r4 .r2 0,
  .jne .r3 (.reg .r4) 172,
  .ldx .dword .r3 .r1 SIZE_OF_U64,
  .ldx .dword .r4 .r2 SIZE_OF_U64,
  .jne .r3 (.reg .r4) 172,
  .ldx .dword .r3 .r1 SIZE_OF_U64_2X,
  .ldx .dword .r4 .r2 SIZE_OF_U64_2X,
  .jne .r3 (.reg .r4) 172,
  .ldx .dword .r3 .r1 SIZE_OF_U64_3X,
  .ldx .dword .r4 .r2 SIZE_OF_U64_3X,
  .jne .r3 (.reg .r4) 172,
  .exit,
  .mov32 .r0 (.imm E_USER_DATA_LEN),
  .exit,
  .mov32 .r0 (.imm E_PDA_DATA_LEN),
  .exit,
  .mov32 .r0 (.imm E_SYSTEM_PROGRAM_DATA_LEN),
  .exit,
  .mov32 .r0 (.imm E_PDA_DUPLICATE),
  .exit,
  .mov32 .r0 (.imm E_SYSTEM_PROGRAM_DUPLICATE),
  .exit,
  .mov32 .r0 (.imm E_PDA_MISMATCH),
  .exit,
  .mov32 .r0 (.imm E_INVALID_INSTRUCTION_DATA_LEN),
  .exit,
  .mov32 .r0 (.imm E_UNABLE_TO_DERIVE_PDA),
  .exit
]

end CounterProg
