-- Auto-generated by qedgen asm2lean from transfer.s
-- DO NOT EDIT — regenerate with: qedgen asm2lean --input transfer.s

import QEDGen.Solana.SBPF

namespace TransferProg

open QEDGen.Solana.SBPF

/-! ## .equ constants -/

abbrev E_N_ACCOUNTS : Nat := 1
abbrev E_DATA_LENGTH_NONZERO_SENDER : Nat := 2
abbrev E_DUPLICATE_ACCOUNT_RECIPIENT : Nat := 3
abbrev E_DATA_LENGTH_NONZERO_RECIPIENT : Nat := 4
abbrev E_DUPLICATE_ACCOUNT_SYSTEM_PROGRAM : Nat := 5
abbrev E_INSTRUCTION_DATA_LENGTH : Nat := 6
abbrev E_INSUFFICIENT_LAMPORTS : Nat := 7
abbrev STACK_SYSTEM_PROGRAM_PUBKEY_OFFSET : Nat := 232
abbrev STACK_INSN_OFFSET : Nat := 200
abbrev STACK_INSN_DATA_OFFSET : Nat := 160
abbrev STACK_ACCT_METAS_OFFSET : Nat := 144
abbrev STACK_ACCT_INFOS_OFFSET : Nat := 112
abbrev N_ACCOUNTS_OFFSET : Int := 0
abbrev N_ACCOUNTS_EXPECTED : Nat := 3
abbrev NON_DUP_MARKER : Nat := 0xff
abbrev DATA_LENGTH_ZERO : Nat := 0
abbrev SENDER_LAMPORTS_OFFSET : Int := 80
abbrev SENDER_DATA_LENGTH_OFFSET : Int := 88
abbrev RECIPIENT_OFFSET : Int := 10344
abbrev RECIPIENT_DATA_LENGTH_OFFSET : Int := 10424
abbrev SYSTEM_PROGRAM_OFFSET : Int := 20680
abbrev INSTRUCTION_DATA_LENGTH_OFFSET : Int := 31032
abbrev INSTRUCTION_DATA_LENGTH_EXPECTED : Nat := 8
abbrev INSTRUCTION_DATA_OFFSET : Int := 31040

/-! ## Program -/

@[simp] def prog : Program := #[
  .ldx .dword .r2 .r1 N_ACCOUNTS_OFFSET,           -- 0: entrypoint
  .jne .r2 (.imm N_ACCOUNTS_EXPECTED) 17,          -- 1
  .ldx .dword .r2 .r1 SENDER_DATA_LENGTH_OFFSET,   -- 2
  .jne .r2 (.imm DATA_LENGTH_ZERO) 19,             -- 3
  .ldx .byte .r2 .r1 RECIPIENT_OFFSET,             -- 4
  .jne .r2 (.imm NON_DUP_MARKER) 21,               -- 5
  .ldx .dword .r2 .r1 RECIPIENT_DATA_LENGTH_OFFSET,-- 6
  .jne .r2 (.imm DATA_LENGTH_ZERO) 23,             -- 7
  .ldx .byte .r2 .r1 SYSTEM_PROGRAM_OFFSET,        -- 8
  .jne .r2 (.imm NON_DUP_MARKER) 25,               -- 9
  .ldx .dword .r4 .r1 INSTRUCTION_DATA_LENGTH_OFFSET,-- 10
  .jne .r4 (.imm INSTRUCTION_DATA_LENGTH_EXPECTED) 27,-- 11
  .ldx .dword .r4 .r1 INSTRUCTION_DATA_OFFSET,     -- 12
  .ldx .dword .r2 .r1 SENDER_LAMPORTS_OFFSET,      -- 13
  .jlt .r2 (.reg .r4) 29,                          -- 14
  .call .sol_invoke_signed,                        -- 15
  .exit,                                           -- 16
  .mov64 .r0 (.imm 1),                             -- 17: e_n_accounts
  .exit,                                           -- 18
  .mov64 .r0 (.imm 2),                             -- 19: e_data_length_nonzero_sender
  .exit,                                           -- 20
  .mov64 .r0 (.imm 3),                             -- 21: e_duplicate_account_recipient
  .exit,                                           -- 22
  .mov64 .r0 (.imm 4),                             -- 23: e_data_length_nonzero_recipient
  .exit,                                           -- 24
  .mov64 .r0 (.imm 5),                             -- 25: e_duplicate_account_system_program
  .exit,                                           -- 26
  .mov64 .r0 (.imm 6),                             -- 27: e_instruction_data_length
  .exit,                                           -- 28
  .mov64 .r0 (.imm 7),                             -- 29: e_insufficient_lamports
  .exit                                             -- 30
]

end TransferProg
